////
// Copyright 2009-2015 ETAS
// ESDL file generated at Thu Jul 09 15:06:23 CEST 2015 by ETAS SCODE Tool V1.5
// Source: C:/Projects/GFA/work/01_HVAC_Applicaion/01_SCODE/Export_ESDL

// Generated by code generation. Do not edit!

package System.Scode;

type ET_Request_VentilationEnum is enum {

	
	ET_Off = 1,
	ET_Automatic = 2,
	ET_Max = 3
	
};

