/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.APP.APP_LeverLights
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_APP_LEVERLIGHTS_EVB_H_
#define _ASD_APP_LEVERLIGHTS_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"
#include "APP_LightDutySwitch_EVB.h"
#include "LIB_TimerUp_EVB.h"
#include "T_LeverIn_EVB.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'APP_LEVERLIGHTS_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'EFLASH'
 * ---------------------------------------------------------------------------*/
struct APP_LEVERLIGHTS_EVB_EFLASH_SUBSTRUCT {
   uint16 APP_FLASHOFFDUTY;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_FLASHONDUTY;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_FLASHTOGGLETIME;	/* min=0.0, max=65.53, esdl_f0_001, limit=yes */
   struct APP_LIGHTDUTYSWITCH_EVB_EFLASH_SUBSTRUCT APP_LightDuty;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'APP_LEVERLIGHTS_EVB'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'APP_LEVERLIGHTS_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IRAM'
 * ---------------------------------------------------------------------------*/
struct APP_LEVERLIGHTS_EVB_IRAM_SUBSTRUCT {
   uint16 APP_DriveDuty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_FlashDuty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_FlashTime;	/* min=0.0, max=65.53, esdl_f0_001, limit=yes */
   uint16 APP_ManualDuty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_NeutralDuty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_ParkDuty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_ReverseDuty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   uint16 APP_SportDuty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   boolean APP_Backlight;	/* min=0, max=1, Identity, limit=yes */
   boolean APP_FlashState;	/* min=0, max=1, Identity, limit=yes */
   boolean APP_TCMLinkOkay;	/* min=0, max=1, Identity, limit=yes */
   struct LIB_TIMERUP_EVB_IRAM_SUBSTRUCT APP_FlashCounter;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'APP_LEVERLIGHTS_EVB'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'APP_LEVERLIGHTS_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IFLASH'
 * ---------------------------------------------------------------------------*/
struct APP_LEVERLIGHTS_EVB {
   struct APP_LEVERLIGHTS_EVB_EFLASH_SUBSTRUCT * APP_LEVERLIGHTS_EVB_EFLASH;
   struct APP_LEVERLIGHTS_EVB_IRAM_SUBSTRUCT * APP_LEVERLIGHTS_EVB_IRAM;
   struct LIB_TIMERUP_EVB APP_FlashCounter;
   struct APP_LIGHTDUTYSWITCH_EVB APP_LightDuty;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'APP_LEVERLIGHTS_EVB'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ........................APP_LEVERLIGHTS_EVB */
#define _APP_LEVERLIGHTS_EVB_TYPE_DEF_




/* forward declaration of types used for method arguments */
#ifndef _T_LEVERIN_EVB_TYPE_DEF_
struct T_LEVERIN_EVB;
#endif

/******************************************************************************
 * BEGIN: declaration of global C functions defined by class APP_LEVERLIGHTS_EVB
 ******************************************************************************/
extern void APP_LEVERLIGHTS_EVB_APP_LightCtrl (
               struct APP_LEVERLIGHTS_EVB * self,
   /* IN    */ struct T_LEVERIN_EVB *       IN_LeverLights,
   /* IN    */ boolean                      IN_Backlight
   );



#endif /* _ASD_APP_LEVERLIGHTS_EVB_H_ */
