/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.APP.APP
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_APP_EVB_H_
#define _ASD_APP_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"
#include "APP_LeverLights_EVB.h"
#include "APP_LeverSelection_EVB.h"
#include "APP_RGBControl_EVB.h"
#include "APP_Sanity_EVB.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'APP_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'EFLASH'
 * ---------------------------------------------------------------------------*/
struct APP_EVB_EFLASH_SUBSTRUCT {
   struct APP_LEVERLIGHTS_EVB_EFLASH_SUBSTRUCT APP_LeverLightControl;
   struct APP_LEVERSELECTION_EVB_EFLASH_SUBSTRUCT APP_LeverSelect;
   struct APP_RGBCONTROL_EVB_EFLASH_SUBSTRUCT APP_RGBSM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'APP_EVB'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'APP_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IRAM'
 * ---------------------------------------------------------------------------*/
struct APP_EVB_IRAM_SUBSTRUCT {
   sint16 APP_SpeedOperand1;	/* min=-32768.0, max=32767.0, f_0bn0, limit=yes */
   sint16 APP_SpeedOperand2;	/* min=-32768.0, max=32767.0, f_0bn0, limit=yes */
   sint16 APP_SpeedSubtraction;	/* min=-32768.0, max=32767.0, f_0bn0, limit=yes */
   sint16 APP_SpeedSum;	/* min=-32768.0, max=32767.0, f_0bn0, limit=yes */
   boolean APP_Toggle;	/* min=0, max=1, Identity, limit=yes */
   struct APP_LEVERLIGHTS_EVB_IRAM_SUBSTRUCT APP_LeverLightControl;
   struct APP_LEVERSELECTION_EVB_IRAM_SUBSTRUCT APP_LeverSelect;
   struct APP_RGBCONTROL_EVB_IRAM_SUBSTRUCT APP_RGBSM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'APP_EVB'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'APP_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IFLASH'
 * ---------------------------------------------------------------------------*/
struct APP_EVB {
   struct APP_LEVERLIGHTS_EVB APP_LeverLightControl;
   struct APP_LEVERSELECTION_EVB APP_LeverSelect;
   struct APP_RGBCONTROL_EVB APP_RGBSM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'APP_EVB'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....................................APP_EVB */
#define _APP_EVB_TYPE_DEF_




/* forward declaration of substruct variable 'APP_EFLASH' */
/* containing 'EFLASH' memory class tree */
extern struct APP_EVB_EFLASH_SUBSTRUCT __attribute__ ((section (".par_ram"))) APP_EFLASH;

/* forward declaration of substruct variable 'APP_IRAM' */
/* containing 'IRAM' memory class tree */
extern struct APP_EVB_IRAM_SUBSTRUCT APP_IRAM;

/* forward declaration of component variable 'APP' */
/* containing 'IFLASH' memory class tree */
extern struct APP_EVB APP;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module APP_EVB
 ******************************************************************************/
extern void APP_EVB_APP_10ms (void);
extern void APP_EVB_APP_1ms (void);



#endif /* _ASD_APP_EVB_H_ */
