/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.APP.APP_LeverLights
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "APP_LeverLights_EVB.h"
#include "S32K144Build_ARM_ArithmeticServices_EVB.h"
#include "T_LeverIn_EVB.h"


/******************************************************************************
 * BEGIN: Generation Information
 *-----------------------------------------------------------------------------
 * Component:................Class
 * Name:....................."APP_LeverLights"
 * Implementation:..........."EVB"
 * Dataset:.................."esdl_Data_Default"
 * Specification:............ESDL
 * Version:..................<empty String>
 * Repository Path:..........<empty String>
 * Library Path:............."\ascet\APP"
 *-----------------------------------------------------------------------------
 * Project Name:............."S32K144Build_ARM_ArithmeticServices"
 * Project Library Path:....."\_project\"
 *-----------------------------------------------------------------------------
 * Generation Date:..........02/12/2020
 * Generation Time:..........11:47:50
 *-----------------------------------------------------------------------------
 * ASCET Version:............V7.5.0
 * ASCET-MD Version:.........V7.5.0
 * ASCET-RP Version:.........not installed
 * ASCET-SE Version:.........V6.4.4-0197
 *-----------------------------------------------------------------------------
 * END: Generation Information
 ******************************************************************************/



/******************************************************************************
 * BEGIN: Project Options "Build"/"Code"
 *-----------------------------------------------------------------------------
 *    Build
 *-----------------------------------------------------------------------------
 * Code Generator:...........Object Based Controller Implementation
 * Compiler:.................Virtual ESDL Compiler
 * Operating System:.........GENERIC_OSEK
 * Target:...................ANSI-C for ESDL
 *-----------------------------------------------------------------------------
 *    Code
 *-----------------------------------------------------------------------------
 * Add Comment with Generation Information for each Component [true]: true
 * Add Comment with Implementation Information for each Assignment Statement [true]: true
 * Add Comment with Specification Source for each Statement [true]:..true
 * Add parenthesis for readability [true]:...........................true
 * Allow References without Init Value [false]:......................false
 * Casting [MISRA]:..................................................MISRA
 * Force Parenthesis for Binary Logical Operators [true]:............true
 * Generate Define Directives for Enum Values [false]:...............false
 * Prefix for Component Names [<empty String>]:......................<empty String>
 * Protected against division by zero [true]:........................true
 * Protected Division against Signed Overflow [true]:................true
 * Protected Vector Indices [true]:..................................true
 * Result on Division by Zero [numerator]:...........................numerator
 * Use Redundant Data Storage [true]:................................true
 *-----------------------------------------------------------------------------
 *    Code.Compiler
 *-----------------------------------------------------------------------------
 * Division truncation direction [Zero (T-division)]:................Zero (T-division)
 * Inline directive [<empty String>]:................................<empty String>
 * Integer Bit Size [32]:............................................32
 * Private directive [<empty String>]:...............................<empty String>
 * Public directive [<empty String>]:................................<empty String>
 *-----------------------------------------------------------------------------
 *    Code.FixedPoint
 *-----------------------------------------------------------------------------
 * Allow Double bit Size for Division Numerators [true]:.............true
 * Arithmetic Service Set [<None>]:..................................example
 * Generate Float Limiter on Assignment [false]:.....................false
 * Generate Round Operation on float to integer Assignment [true]:...true
 * Maximum bit Length (int) [32]:....................................32
 * New Behaviour for Discrete Types [true]:..........................true
 * Temp Vars always 32 bit (integer) [false]:........................false
 * Use power of 2 approximations of literals [false]:................true
 * Use SHIFT Operation on Signed Values instead of DIV Operation [false]: false
 * Use SHIFT Operation on Signed Values instead of MUL Operation [false]: false
 *-----------------------------------------------------------------------------
 *    Code.Optimizations
 *-----------------------------------------------------------------------------
 * Auto-inline private methods (Smaller code-size - may be changed locally) [false]: false
 * Common Subexpression Elimination [false]:.........................true
 * Dead Code Elimination [Comment]:..................................Comment
 * Disable BDE Temp Variable Generation [false]:.....................true
 * Generate well-formed switch [true]:...............................true
 * Hierarchical Code-Generation (may be changed locally) [false]:....false
 * Initialise history variable with zero [false]:....................false
 * Optimize Direct Access Methods (Multiple Levels) [false]:.........true
 * Optimize Direct Access Methods (One Level) [false]:...............true
 * Optimize Static Actions (Restricted Modelling) [true]:............false
 * Outline Generated Methods (may be changed locally) [false]:.......false
 *-----------------------------------------------------------------------------
 *    Code.Production
 *-----------------------------------------------------------------------------
 * Add Implementation Definitions [true]:............................true
 * Generate Access Methods for dT (Alternative: use OS dT directly) [true]: false
 * Generate Data Structures [USELOCAL]:..............................USELOCAL
 * Generate Map File [true]:.........................................false
 * Generate OS Configuration [true]:.................................true
 * Use OID for Generation of Component Names [false]:................false
 *-----------------------------------------------------------------------------
 *    Station.Build
 *-----------------------------------------------------------------------------
 * Use Customized Data Type Names [false]:...........................true
 *-----------------------------------------------------------------------------
 *    TargetSettings.G_ANSI.Build
 *-----------------------------------------------------------------------------
 * Compile Unused Data [false]:......................................false
 * Cont Implementation Type [SINGLE]:................................SINGLE
 * Force no self pointer optimization [false]:.......................false
 * Function Name of memcpy [memcpy]:.................................memcpy
 * Generate define for constants [false]:............................false
 * Generate Method Body [Use Component Settings]:....................Use Component Settings
 * Generating Access Macros [true]:..................................true
 * Generating Access Macros for Messages [false]:....................false
 * Generating Message Copy [true]:...................................true
 * Generating SCOOP-IX [false]:......................................false
 * Matrix Orientation [columnMajor]:.................................columnMajor
 * Number of dimensions for fixed matrixes [1D]:.....................1D
 * Optimize Unused Code [false]:.....................................true
 * Place Array/Matrix reference structure of Parameters on the Stack [false]: false
 * Place Array/Matrix reference structure of Variables on the Stack [false]: false
 * Resolve System Constants [compileTime]:...........................compileTime
 * Using External Build Tool [false]:................................false
 * Variant Coded Data Structures [false]:............................false
 *-----------------------------------------------------------------------------
 * END: Project Options "Build"/"Code"
 ******************************************************************************/


/******************************************************************************
 * BEGIN: ASCET-SE AddOn Options
 * ----------------------------------------------------------------------------
 *     Code
 * ----------------------------------------------------------------------------
 * checkMemSectionVolatility [true]:.................................false
 * checkMultipleSend [false]:........................................false
 * distribVarMemClass ["DISTRRAM"]:.................................."DISTRRAM"
 * genAlwaysInitValues [false]:......................................true
 * genLogicElementsAs [PACKED_BITFIELD]:.............................PACKED_BITFIELD
 * genObjList [false]:...............................................false
 * implInfoComments [true]:..........................................true
 * initTaskMemClass ["ASD_INIT_TASK_MEM"]:..........................."ASD_INIT_TASK_MEM"
 * isrMemClass ["ASD_ISR_MEM"]:......................................"ASD_ISR_MEM"
 * mainMemClass ["ASD_EXT_CODE_MEM"]:................................"ASD_EXT_CODE_MEM"
 * paramAsSysConst [false]:..........................................false
 * pragmaMemClassAtDecl [false]:.....................................false
 * pragmaMemClassEnabled [true]:.....................................true
 * referenceMemClass ["REFRAM"]:....................................."REFRAM"
 * shortNames [false]:...............................................false
 * taskMemClass ["ASD_TASK_MEM"]:...................................."CODE"
 * virtualParameterMemClass ["VIRT_PARAM"]:.........................."VIRT_PARAM"
 * ----------------------------------------------------------------------------
 *     Code.Appearance
 * ----------------------------------------------------------------------------
 * braceLineFeed [true]:.............................................true
 * genDate [<undef>]:................................................<undef>
 * genTime [<undef>]:................................................<undef>
 * generateSignatureDecorationComments [true]:.......................true
 * lineFeedPosition [LEFT]:..........................................LEFT
 * maxIdentLength [0]:...............................................40
 * maxRightLength [60]:..............................................60
 * minLeftLength [8]:................................................8
 * preventIndentStructInit [true]:...................................true
 * ----------------------------------------------------------------------------
 *     OS
 * ----------------------------------------------------------------------------
 * MemAllocKeyword_ShortnameAndAlignment [true]:.....................true
 * Os-Config-C_gen_declaration_alarms [false]:.......................false
 * Os-Config-C_gen_declaration_appmodes [false]:.....................false
 * Os-Config-C_gen_dt_calc [false]:..................................true
 * Os-Config-C_gen_initCOM [false]:..................................false
 * Os-Config-C_gen_inittask [false]:.................................false
 * Os-Config-C_gen_main [false]:.....................................false
 * Os-Config-C_gen_process_container [false]:........................true
 * Os-Config-C_gen_startuphook [false]:..............................true
 * asd_exclusive_area ["ASD_EXCLUSIVE_AREA"]:........................"ASCET_exclusive_area"
 * messageDoInit [false]:............................................true
 * messageExternalMessageCopies [false]:.............................false
 * messageGenOSEKDeclarations [true]:................................false
 * messageIgnoreUsageInInitTask [false]:.............................false
 * messageOverloadInitValues [<undef>]:..............................<undef>
 * messageUsageVariant [OPT_COPY]:...................................NON_OPT_COPY
 * modularMessageUse [false]:........................................false
 * osAppModePattern ["%name%"]:......................................"appmode_%name%"
 * osStartupFunction [<undef>]:......................................<undef>
 * ----------------------------------------------------------------------------
 *     OS.OIL
 * ----------------------------------------------------------------------------
 * OIL-COOP-RESOURCE-name ["ASD_Cooperative_Res"]:..................."ASD_Cooperative_Res"
 * OIL-outputFile ["temp.oil"]:......................................"temp.oil"
 * ----------------------------------------------------------------------------
 *     SERAP
 * ----------------------------------------------------------------------------
 * SERAPRefPageMemoryClass ["SERAP_REF"]:............................"SERAP_REF"
 * SERAPWorkPageMemoryClass ["SERAP_WORK"]:.........................."SERAP_WORK"
 * serap [false]:....................................................false
 * serapEmbedded [true]:.............................................true
 * ----------------------------------------------------------------------------
 *     Virtual Address Tables
 * ----------------------------------------------------------------------------
 * addressTableMemoryClass ["VATROM"]:..............................."VATROM"
 * ----------------------------------------------------------------------------
 * END: ASCET-SE AddOn Options
 ******************************************************************************/


/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define _APP_Backlight (self->APP_LEVERLIGHTS_EVB_IRAM->APP_Backlight)
#define _APP_DriveDuty (self->APP_LEVERLIGHTS_EVB_IRAM->APP_DriveDuty)
#define _APP_FlashCounter_REF_ (&(self->APP_FlashCounter))
#define _APP_FlashDuty (self->APP_LEVERLIGHTS_EVB_IRAM->APP_FlashDuty)
#define _APP_FLASHOFFDUTY (self->APP_LEVERLIGHTS_EVB_EFLASH->APP_FLASHOFFDUTY)
#define _APP_FLASHONDUTY (self->APP_LEVERLIGHTS_EVB_EFLASH->APP_FLASHONDUTY)
#define _APP_FlashState (self->APP_LEVERLIGHTS_EVB_IRAM->APP_FlashState)
#define _APP_FlashTime (self->APP_LEVERLIGHTS_EVB_IRAM->APP_FlashTime)
#define _APP_FLASHTOGGLETIME (self->APP_LEVERLIGHTS_EVB_EFLASH->APP_FLASHTOGGLETIME)
#define _APP_LightDuty_REF_ (&(self->APP_LightDuty))
#define _APP_ManualDuty (self->APP_LEVERLIGHTS_EVB_IRAM->APP_ManualDuty)
#define _APP_NeutralDuty (self->APP_LEVERLIGHTS_EVB_IRAM->APP_NeutralDuty)
#define _APP_ParkDuty (self->APP_LEVERLIGHTS_EVB_IRAM->APP_ParkDuty)
#define _APP_ReverseDuty (self->APP_LEVERLIGHTS_EVB_IRAM->APP_ReverseDuty)
#define _APP_SportDuty (self->APP_LEVERLIGHTS_EVB_IRAM->APP_SportDuty)
#define _APP_TCMLinkOkay (self->APP_LEVERLIGHTS_EVB_IRAM->APP_TCMLinkOkay)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'APP_LEVERLIGHTS_EVB_APP_LightCtrl'
 * ----------------------------------------------------------------------------
 * model name:...................................'APP_LightCtrl'
 * memory class:.................................'ICODE'
 * ---------------------------------------------------------------------------*/
/* public APP_LightCtrl (IN_LeverLights::T_LeverIn;IN_Backlight::log)  */

void APP_LEVERLIGHTS_EVB_APP_LightCtrl (
               struct APP_LEVERLIGHTS_EVB * self,
   /* IN    */ struct T_LEVERIN_EVB *       IN_LeverLights,
   /* IN    */ boolean                      IN_Backlight
   )
{
   /* APP_LightCtrl: line #4  */
   /* assignment to APP_FlashTime: min=0, max=65530, hex=1000phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_FlashTime
      = LIB_TIMERUP_EVB_LIB_Time(_APP_FlashCounter_REF_, _APP_FlashTime >= _APP_FLASHTOGGLETIME, SY_10MS);
   /* APP_LightCtrl: line #7  */
   if (_APP_FlashTime == 0U)
   {
      _APP_FlashState = !_APP_FlashState;
   } /* end if */
   /* APP_LightCtrl: line #10  */
   /* assignment to APP_FlashDuty: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_FlashDuty = ((_APP_FlashState) ? _APP_FLASHONDUTY : _APP_FLASHOFFDUTY);
   /* APP_LightCtrl: line #17  */
   _APP_TCMLinkOkay = IN_LeverLights->TCM_Status == 1U;
   /* APP_LightCtrl: line #20  */
   _APP_Backlight
      = ((IN_LeverLights->TCM_BackLight == 3U) ? IN_Backlight : (IN_LeverLights->TCM_BackLight != 1U));
   /* APP_LightCtrl: line #27  */
   /* assignment to APP_ParkDuty: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_ParkDuty
      = APP_LIGHTDUTYSWITCH_EVB_APP_LightDuty(_APP_LightDuty_REF_, IN_LeverLights->TCM_ParkLight, _APP_FlashDuty, _APP_Backlight, _APP_TCMLinkOkay);
   /* APP_LightCtrl: line #30  */
   /* assignment to APP_NeutralDuty: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_NeutralDuty
      = APP_LIGHTDUTYSWITCH_EVB_APP_LightDuty(_APP_LightDuty_REF_, IN_LeverLights->TCM_NeutralLight, _APP_FlashDuty, _APP_Backlight, _APP_TCMLinkOkay);
   /* APP_LightCtrl: line #33  */
   /* assignment to APP_ReverseDuty: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_ReverseDuty
      = APP_LIGHTDUTYSWITCH_EVB_APP_LightDuty(_APP_LightDuty_REF_, IN_LeverLights->TCM_ReverseLight, _APP_FlashDuty, _APP_Backlight, _APP_TCMLinkOkay);
   /* APP_LightCtrl: line #36  */
   /* assignment to APP_DriveDuty: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_DriveDuty
      = APP_LIGHTDUTYSWITCH_EVB_APP_LightDuty(_APP_LightDuty_REF_, IN_LeverLights->TCM_DriveLight, _APP_FlashDuty, _APP_Backlight, _APP_TCMLinkOkay);
   /* APP_LightCtrl: line #39  */
   /* assignment to APP_SportDuty: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_SportDuty
      = APP_LIGHTDUTYSWITCH_EVB_APP_LightDuty(_APP_LightDuty_REF_, IN_LeverLights->TCM_SportLight, _APP_FlashDuty, _APP_Backlight, _APP_TCMLinkOkay);
   /* APP_LightCtrl: line #42  */
   /* assignment to APP_ManualDuty: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_ManualDuty
      = APP_LIGHTDUTYSWITCH_EVB_APP_LightDuty(_APP_LightDuty_REF_, IN_LeverLights->TCM_ManualLight, _APP_FlashDuty, _APP_Backlight, _APP_TCMLinkOkay);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'APP_LEVERLIGHTS_EVB_APP_LightCtrl'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



