/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.APP.APP
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "APP_EVB.h"
#include "APPInterface_EVB.h"
#include "INInterface_EVB.h"
#include "T_InputCapture_EVB.h"
#include "T_LeverIn_EVB.h"
#include "T_LeverOut_EVB.h"


/******************************************************************************
 * BEGIN: Generation Information
 *-----------------------------------------------------------------------------
 * Component:................Module
 * Name:....................."APP"
 * Implementation:..........."EVB"
 * Dataset:.................."esdl_Data_Default"
 * Specification:............ESDL
 * Version:..................<empty String>
 * Repository Path:..........<empty String>
 * Library Path:............."\ascet\APP"
 *-----------------------------------------------------------------------------
 * Project Name:............."S32K144Build_ARM_ArithmeticServices"
 * Project Library Path:....."\_project\"
 *-----------------------------------------------------------------------------
 * Generation Date:..........02/12/2020
 * Generation Time:..........11:47:50
 *-----------------------------------------------------------------------------
 * ASCET Version:............V7.5.0
 * ASCET-MD Version:.........V7.5.0
 * ASCET-RP Version:.........not installed
 * ASCET-SE Version:.........V6.4.4-0197
 *-----------------------------------------------------------------------------
 * END: Generation Information
 ******************************************************************************/



/******************************************************************************
 * BEGIN: Project Options "Build"/"Code"
 *-----------------------------------------------------------------------------
 *    Build
 *-----------------------------------------------------------------------------
 * Code Generator:...........Object Based Controller Implementation
 * Compiler:.................Virtual ESDL Compiler
 * Operating System:.........GENERIC_OSEK
 * Target:...................ANSI-C for ESDL
 *-----------------------------------------------------------------------------
 *    Code
 *-----------------------------------------------------------------------------
 * Add Comment with Generation Information for each Component [true]: true
 * Add Comment with Implementation Information for each Assignment Statement [true]: true
 * Add Comment with Specification Source for each Statement [true]:..true
 * Add parenthesis for readability [true]:...........................true
 * Allow References without Init Value [false]:......................false
 * Casting [MISRA]:..................................................MISRA
 * Force Parenthesis for Binary Logical Operators [true]:............true
 * Generate Define Directives for Enum Values [false]:...............false
 * Prefix for Component Names [<empty String>]:......................<empty String>
 * Protected against division by zero [true]:........................true
 * Protected Division against Signed Overflow [true]:................true
 * Protected Vector Indices [true]:..................................true
 * Result on Division by Zero [numerator]:...........................numerator
 * Use Redundant Data Storage [true]:................................true
 *-----------------------------------------------------------------------------
 *    Code.Compiler
 *-----------------------------------------------------------------------------
 * Division truncation direction [Zero (T-division)]:................Zero (T-division)
 * Inline directive [<empty String>]:................................<empty String>
 * Integer Bit Size [32]:............................................32
 * Private directive [<empty String>]:...............................<empty String>
 * Public directive [<empty String>]:................................<empty String>
 *-----------------------------------------------------------------------------
 *    Code.FixedPoint
 *-----------------------------------------------------------------------------
 * Allow Double bit Size for Division Numerators [true]:.............true
 * Arithmetic Service Set [<None>]:..................................example
 * Generate Float Limiter on Assignment [false]:.....................false
 * Generate Round Operation on float to integer Assignment [true]:...true
 * Maximum bit Length (int) [32]:....................................32
 * New Behaviour for Discrete Types [true]:..........................true
 * Temp Vars always 32 bit (integer) [false]:........................false
 * Use power of 2 approximations of literals [false]:................true
 * Use SHIFT Operation on Signed Values instead of DIV Operation [false]: false
 * Use SHIFT Operation on Signed Values instead of MUL Operation [false]: false
 *-----------------------------------------------------------------------------
 *    Code.Optimizations
 *-----------------------------------------------------------------------------
 * Auto-inline private methods (Smaller code-size - may be changed locally) [false]: false
 * Common Subexpression Elimination [false]:.........................true
 * Dead Code Elimination [Comment]:..................................Comment
 * Disable BDE Temp Variable Generation [false]:.....................true
 * Generate well-formed switch [true]:...............................true
 * Hierarchical Code-Generation (may be changed locally) [false]:....false
 * Initialise history variable with zero [false]:....................false
 * Optimize Direct Access Methods (Multiple Levels) [false]:.........true
 * Optimize Direct Access Methods (One Level) [false]:...............true
 * Optimize Static Actions (Restricted Modelling) [true]:............false
 * Outline Generated Methods (may be changed locally) [false]:.......false
 *-----------------------------------------------------------------------------
 *    Code.Production
 *-----------------------------------------------------------------------------
 * Add Implementation Definitions [true]:............................true
 * Generate Access Methods for dT (Alternative: use OS dT directly) [true]: false
 * Generate Data Structures [USELOCAL]:..............................USELOCAL
 * Generate Map File [true]:.........................................false
 * Generate OS Configuration [true]:.................................true
 * Use OID for Generation of Component Names [false]:................false
 *-----------------------------------------------------------------------------
 *    Station.Build
 *-----------------------------------------------------------------------------
 * Use Customized Data Type Names [false]:...........................true
 *-----------------------------------------------------------------------------
 *    TargetSettings.G_ANSI.Build
 *-----------------------------------------------------------------------------
 * Compile Unused Data [false]:......................................false
 * Cont Implementation Type [SINGLE]:................................SINGLE
 * Force no self pointer optimization [false]:.......................false
 * Function Name of memcpy [memcpy]:.................................memcpy
 * Generate define for constants [false]:............................false
 * Generate Method Body [Use Component Settings]:....................Use Component Settings
 * Generating Access Macros [true]:..................................true
 * Generating Access Macros for Messages [false]:....................false
 * Generating Message Copy [true]:...................................true
 * Generating SCOOP-IX [false]:......................................false
 * Matrix Orientation [columnMajor]:.................................columnMajor
 * Number of dimensions for fixed matrixes [1D]:.....................1D
 * Optimize Unused Code [false]:.....................................true
 * Place Array/Matrix reference structure of Parameters on the Stack [false]: false
 * Place Array/Matrix reference structure of Variables on the Stack [false]: false
 * Resolve System Constants [compileTime]:...........................compileTime
 * Using External Build Tool [false]:................................false
 * Variant Coded Data Structures [false]:............................false
 *-----------------------------------------------------------------------------
 * END: Project Options "Build"/"Code"
 ******************************************************************************/


/******************************************************************************
 * BEGIN: ASCET-SE AddOn Options
 * ----------------------------------------------------------------------------
 *     Code
 * ----------------------------------------------------------------------------
 * checkMemSectionVolatility [true]:.................................false
 * checkMultipleSend [false]:........................................false
 * distribVarMemClass ["DISTRRAM"]:.................................."DISTRRAM"
 * genAlwaysInitValues [false]:......................................true
 * genLogicElementsAs [PACKED_BITFIELD]:.............................PACKED_BITFIELD
 * genObjList [false]:...............................................false
 * implInfoComments [true]:..........................................true
 * initTaskMemClass ["ASD_INIT_TASK_MEM"]:..........................."ASD_INIT_TASK_MEM"
 * isrMemClass ["ASD_ISR_MEM"]:......................................"ASD_ISR_MEM"
 * mainMemClass ["ASD_EXT_CODE_MEM"]:................................"ASD_EXT_CODE_MEM"
 * paramAsSysConst [false]:..........................................false
 * pragmaMemClassAtDecl [false]:.....................................false
 * pragmaMemClassEnabled [true]:.....................................true
 * referenceMemClass ["REFRAM"]:....................................."REFRAM"
 * shortNames [false]:...............................................false
 * taskMemClass ["ASD_TASK_MEM"]:...................................."CODE"
 * virtualParameterMemClass ["VIRT_PARAM"]:.........................."VIRT_PARAM"
 * ----------------------------------------------------------------------------
 *     Code.Appearance
 * ----------------------------------------------------------------------------
 * braceLineFeed [true]:.............................................true
 * genDate [<undef>]:................................................<undef>
 * genTime [<undef>]:................................................<undef>
 * generateSignatureDecorationComments [true]:.......................true
 * lineFeedPosition [LEFT]:..........................................LEFT
 * maxIdentLength [0]:...............................................40
 * maxRightLength [60]:..............................................60
 * minLeftLength [8]:................................................8
 * preventIndentStructInit [true]:...................................true
 * ----------------------------------------------------------------------------
 *     OS
 * ----------------------------------------------------------------------------
 * MemAllocKeyword_ShortnameAndAlignment [true]:.....................true
 * Os-Config-C_gen_declaration_alarms [false]:.......................false
 * Os-Config-C_gen_declaration_appmodes [false]:.....................false
 * Os-Config-C_gen_dt_calc [false]:..................................true
 * Os-Config-C_gen_initCOM [false]:..................................false
 * Os-Config-C_gen_inittask [false]:.................................false
 * Os-Config-C_gen_main [false]:.....................................false
 * Os-Config-C_gen_process_container [false]:........................true
 * Os-Config-C_gen_startuphook [false]:..............................true
 * asd_exclusive_area ["ASD_EXCLUSIVE_AREA"]:........................"ASCET_exclusive_area"
 * messageDoInit [false]:............................................true
 * messageExternalMessageCopies [false]:.............................false
 * messageGenOSEKDeclarations [true]:................................false
 * messageIgnoreUsageInInitTask [false]:.............................false
 * messageOverloadInitValues [<undef>]:..............................<undef>
 * messageUsageVariant [OPT_COPY]:...................................NON_OPT_COPY
 * modularMessageUse [false]:........................................false
 * osAppModePattern ["%name%"]:......................................"appmode_%name%"
 * osStartupFunction [<undef>]:......................................<undef>
 * ----------------------------------------------------------------------------
 *     OS.OIL
 * ----------------------------------------------------------------------------
 * OIL-COOP-RESOURCE-name ["ASD_Cooperative_Res"]:..................."ASD_Cooperative_Res"
 * OIL-outputFile ["temp.oil"]:......................................"temp.oil"
 * ----------------------------------------------------------------------------
 *     SERAP
 * ----------------------------------------------------------------------------
 * SERAPRefPageMemoryClass ["SERAP_REF"]:............................"SERAP_REF"
 * SERAPWorkPageMemoryClass ["SERAP_WORK"]:.........................."SERAP_WORK"
 * serap [false]:....................................................false
 * serapEmbedded [true]:.............................................true
 * ----------------------------------------------------------------------------
 *     Virtual Address Tables
 * ----------------------------------------------------------------------------
 * addressTableMemoryClass ["VATROM"]:..............................."VATROM"
 * ----------------------------------------------------------------------------
 * END: ASCET-SE AddOn Options
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'APP_EFLASH'
 * ----------------------------------------------------------------------------
 * memory class:.................................'EFLASH'
 * model name:...................................'APP'
 * data set:.....................................'APP_EVB_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct APP_EVB_EFLASH_SUBSTRUCT __attribute__ ((section (".par_ram"))) APP_EFLASH = {
   /* substruct: APP_EFLASH.APP_LeverLightControl (modeled as:'APP_LeverLightControl.APP') */
   {
      /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_FLASHOFFDUTY' (modeled as:'APP_FLASHOFFDUTY.APP_LeverLightControl.APP') */
      500U,
      /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_FLASHONDUTY' (modeled as:'APP_FLASHONDUTY.APP_LeverLightControl.APP') */
      9500U,
      /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_FLASHTOGGLETIME' (modeled as:'APP_FLASHTOGGLETIME.APP_LeverLightControl.APP') */
      750U,
      /* substruct: APP_EFLASH.APP_LeverLightControl.APP_LightDuty (modeled as:'APP_LightDuty.APP_LeverLightControl.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_LightDuty.APP_LIGHTOFFNOBACKDUTY' (modeled as:'APP_LIGHTOFFNOBACKDUTY.APP_LightDuty.APP_LeverLightControl.APP') */
         500U,
         /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_LightDuty.APP_LIGHTOFFWITHBACKDUTY' (modeled as:'APP_LIGHTOFFWITHBACKDUTY.APP_LightDuty.APP_LeverLightControl.APP') */
         2500U,
         /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_LightDuty.APP_LIGHTONNOBACKDUTY' (modeled as:'APP_LIGHTONNOBACKDUTY.APP_LightDuty.APP_LeverLightControl.APP') */
         8500U,
         /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_LightDuty.APP_LIGHTONWITHBACKDUTY' (modeled as:'APP_LIGHTONWITHBACKDUTY.APP_LightDuty.APP_LeverLightControl.APP') */
         9500U,
         /* struct element:'APP_EFLASH.APP_LeverLightControl.APP_LightDuty.APP_INVERTDUTY' (modeled as:'APP_INVERTDUTY.APP_LightDuty.APP_LeverLightControl.APP') */
         false
      }
   },
   /* substruct: APP_EFLASH.APP_LeverSelect (modeled as:'APP_LeverSelect.APP') */
   {
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_MINUSSWITCHMAX' (modeled as:'APP_MINUSSWITCHMAX.APP_LeverSelect.APP') */
      19661U,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_MINUSSWITCHMIN' (modeled as:'APP_MINUSSWITCHMIN.APP_LeverSelect.APP') */
      6554U,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_PLUSSWITCHMAX' (modeled as:'APP_PLUSSWITCHMAX.APP_LeverSelect.APP') */
      52428U,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_PLUSSWITCHMIN' (modeled as:'APP_PLUSSWITCHMIN.APP_LeverSelect.APP') */
      39321U,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_ANALOGUEPLUSMINUS' (modeled as:'APP_ANALOGUEPLUSMINUS.APP_LeverSelect.APP') */
      true,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_DRIVESWFITTED' (modeled as:'APP_DRIVESWFITTED.APP_LeverSelect.APP') */
      true,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_MANUALSWFITTED' (modeled as:'APP_MANUALSWFITTED.APP_LeverSelect.APP') */
      true,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_MINUSSWFITTED' (modeled as:'APP_MINUSSWFITTED.APP_LeverSelect.APP') */
      true,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_NEUTRALSWFITTED' (modeled as:'APP_NEUTRALSWFITTED.APP_LeverSelect.APP') */
      true,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_PARKSWFITTED' (modeled as:'APP_PARKSWFITTED.APP_LeverSelect.APP') */
      false,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_PLUSSWFITTED' (modeled as:'APP_PLUSSWFITTED.APP_LeverSelect.APP') */
      true,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_REVERSESWFITTED' (modeled as:'APP_REVERSESWFITTED.APP_LeverSelect.APP') */
      true,
      /* struct element:'APP_EFLASH.APP_LeverSelect.APP_SPORTSWFITTED' (modeled as:'APP_SPORTSWFITTED.APP_LeverSelect.APP') */
      true,
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_DriveSwitchInterp (modeled as:'APP_DriveSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_DriveSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_DriveSwitchInterp.APP_LeverSelect.APP') */
         10000U
      },
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_ManualSwitchInterp (modeled as:'APP_ManualSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_ManualSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_ManualSwitchInterp.APP_LeverSelect.APP') */
         10000U
      },
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_MinusSwitchInterp (modeled as:'APP_MinusSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_MinusSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_MinusSwitchInterp.APP_LeverSelect.APP') */
         10000U
      },
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_NeutralSwitchInterp (modeled as:'APP_NeutralSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_NeutralSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_NeutralSwitchInterp.APP_LeverSelect.APP') */
         10000U
      },
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_ParkSwitchInterp (modeled as:'APP_ParkSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_ParkSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_ParkSwitchInterp.APP_LeverSelect.APP') */
         10000U
      },
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_PlusSwitchInterp (modeled as:'APP_PlusSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_PlusSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_PlusSwitchInterp.APP_LeverSelect.APP') */
         10000U
      },
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_ReverseSwitchInterp (modeled as:'APP_ReverseSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_ReverseSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_ReverseSwitchInterp.APP_LeverSelect.APP') */
         10000U
      },
      /* substruct: APP_EFLASH.APP_LeverSelect.APP_SportSwitchInterp (modeled as:'APP_SportSwitchInterp.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_EFLASH.APP_LeverSelect.APP_SportSwitchInterp.APP_MAXSWITCHPRESSTIME' (modeled as:'APP_MAXSWITCHPRESSTIME.APP_SportSwitchInterp.APP_LeverSelect.APP') */
         10000U
      }
   },
   /* substruct: APP_EFLASH.APP_RGBSM (modeled as:'APP_RGBSM.APP') */
   {
      /* struct element:'APP_EFLASH.APP_RGBSM.APP_LEDRESETTIME' (modeled as:'APP_LEDRESETTIME.APP_RGBSM.APP') */
      8000U,
      /* struct element:'APP_EFLASH.APP_RGBSM.APP_BLUELEDINTENSITY' (modeled as:'APP_BLUELEDINTENSITY.APP_RGBSM.APP') */
      {
         9U,
         {
            0U, 1000U, 2000U, 3000U, 4000U, 5000U, 6000U, 7000U, 8000U
         },
         {
            0U, 0U, 0U, 0U, 150U, 100U, 100U, 0U, 0U
         }
      },
      /* struct element:'APP_EFLASH.APP_RGBSM.APP_GREENLEDINTENSITY' (modeled as:'APP_GREENLEDINTENSITY.APP_RGBSM.APP') */
      {
         9U,
         {
            0U, 1000U, 2000U, 3000U, 4000U, 5000U, 6000U, 7000U, 8000U
         },
         {
            150U, 100U, 75U, 0U, 0U, 50U, 50U, 150U, 150U
         }
      },
      /* struct element:'APP_EFLASH.APP_RGBSM.APP_REDLEDINTENSITY' (modeled as:'APP_REDLEDINTENSITY.APP_RGBSM.APP') */
      {
         9U,
         {
            0U, 1000U, 2000U, 3000U, 4000U, 5000U, 6000U, 7000U, 8000U
         },
         {
            0U, 50U, 75U, 150U, 0U, 0U, 26U, 0U, 0U
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'APP_EFLASH'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'APP_IRAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IRAM'
 * model name:...................................'APP'
 * data set:.....................................'APP_EVB_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct APP_EVB_IRAM_SUBSTRUCT APP_IRAM = {
   /* struct element:'APP_IRAM.APP_SpeedOperand1' (modeled as:'APP_SpeedOperand1.APP') */
   0,
   /* struct element:'APP_IRAM.APP_SpeedOperand2' (modeled as:'APP_SpeedOperand2.APP') */
   0,
   /* struct element:'APP_IRAM.APP_SpeedSubtraction' (modeled as:'APP_SpeedSubtraction.APP') */
   0,
   /* struct element:'APP_IRAM.APP_SpeedSum' (modeled as:'APP_SpeedSum.APP') */
   0,
   /* struct element:'APP_IRAM.APP_Toggle' (modeled as:'APP_Toggle.APP') */
   false,
   /* substruct: APP_IRAM.APP_LeverLightControl (modeled as:'APP_LeverLightControl.APP') */
   {
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_DriveDuty' (modeled as:'APP_DriveDuty.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_FlashDuty' (modeled as:'APP_FlashDuty.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_FlashTime' (modeled as:'APP_FlashTime.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_ManualDuty' (modeled as:'APP_ManualDuty.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_NeutralDuty' (modeled as:'APP_NeutralDuty.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_ParkDuty' (modeled as:'APP_ParkDuty.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_ReverseDuty' (modeled as:'APP_ReverseDuty.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_SportDuty' (modeled as:'APP_SportDuty.APP_LeverLightControl.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_Backlight' (modeled as:'APP_Backlight.APP_LeverLightControl.APP') */
      false,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_FlashState' (modeled as:'APP_FlashState.APP_LeverLightControl.APP') */
      false,
      /* struct element:'APP_IRAM.APP_LeverLightControl.APP_TCMLinkOkay' (modeled as:'APP_TCMLinkOkay.APP_LeverLightControl.APP') */
      false,
      /* substruct: APP_IRAM.APP_LeverLightControl.APP_FlashCounter (modeled as:'APP_FlashCounter.APP_LeverLightControl.APP') */
      {
         /* struct element:'APP_IRAM.APP_LeverLightControl.APP_FlashCounter.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_FlashCounter.APP_LeverLightControl.APP') */
         0U
      }
   },
   /* substruct: APP_IRAM.APP_LeverSelect (modeled as:'APP_LeverSelect.APP') */
   {
      /* struct element:'APP_IRAM.APP_LeverSelect.APP_AnalogueMinus' (modeled as:'APP_AnalogueMinus.APP_LeverSelect.APP') */
      false,
      /* struct element:'APP_IRAM.APP_LeverSelect.APP_AnaloguePlus' (modeled as:'APP_AnaloguePlus.APP_LeverSelect.APP') */
      false,
      /* substruct: APP_IRAM.APP_LeverSelect.APP_LeverSwitch (modeled as:'APP_LeverSwitch.APP_LeverSelect.APP') */
      {
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_DriveSwitch' (modeled as:'LVR_DriveSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_ManualSwitch' (modeled as:'LVR_ManualSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_MinusSwitch' (modeled as:'LVR_MinusSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_NeutralSwitch' (modeled as:'LVR_NeutralSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_ParkSwitch' (modeled as:'LVR_ParkSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_PlusSwitch' (modeled as:'LVR_PlusSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_ReverseSwitch' (modeled as:'LVR_ReverseSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_SportSwitch' (modeled as:'LVR_SportSwitch.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_Status' (modeled as:'LVR_Status.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U,
         /* struct element:'APP_IRAM.APP_LeverSelect.APP_LeverSwitch.LVR_TestResponse' (modeled as:'LVR_TestResponse.APP_LeverSwitch.APP_LeverSelect.APP') */
         0U
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_DriveSwitchInterp (modeled as:'APP_DriveSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_DriveSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_DriveSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_DriveSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_DriveSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_ManualSwitchInterp (modeled as:'APP_ManualSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_ManualSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_ManualSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_ManualSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_ManualSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_MinusSwitchInterp (modeled as:'APP_MinusSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_MinusSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_MinusSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_MinusSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_MinusSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_NeutralSwitchInterp (modeled as:'APP_NeutralSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_NeutralSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_NeutralSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_NeutralSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_NeutralSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_ParkSwitchInterp (modeled as:'APP_ParkSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_ParkSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_ParkSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_ParkSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_ParkSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_PlusSwitchInterp (modeled as:'APP_PlusSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_PlusSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_PlusSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_PlusSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_PlusSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_ReverseSwitchInterp (modeled as:'APP_ReverseSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_ReverseSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_ReverseSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_ReverseSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_ReverseSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      },
      /* substruct: APP_IRAM.APP_LeverSelect.APP_SportSwitchInterp (modeled as:'APP_SportSwitchInterp.APP_LeverSelect.APP') */
      {
         /* substruct: APP_IRAM.APP_LeverSelect.APP_SportSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_SportSwitchInterp.APP_LeverSelect.APP') */
         {
            /* struct element:'APP_IRAM.APP_LeverSelect.APP_SportSwitchInterp.APP_SwitchTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_SwitchTimer.APP_SportSwitchInterp.APP_LeverSelect.APP') */
            0U
         }
      }
   },
   /* substruct: APP_IRAM.APP_RGBSM (modeled as:'APP_RGBSM.APP') */
   {
      /* struct element:'APP_IRAM.APP_RGBSM.APP_BlueDuty' (modeled as:'APP_BlueDuty.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_GreenDuty' (modeled as:'APP_GreenDuty.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_LedTime' (modeled as:'APP_LedTime.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_Pot' (modeled as:'APP_Pot.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_RedDuty' (modeled as:'APP_RedDuty.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_BlueIntensity' (modeled as:'APP_BlueIntensity.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_BlueIntensityMap' (modeled as:'APP_BlueIntensityMap.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_GreenIntensity' (modeled as:'APP_GreenIntensity.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_GreenIntensityMap' (modeled as:'APP_GreenIntensityMap.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_RedIntensity' (modeled as:'APP_RedIntensity.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_RedIntensityMap' (modeled as:'APP_RedIntensityMap.APP_RGBSM.APP') */
      0U,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_Run' (modeled as:'APP_Run.APP_RGBSM.APP') */
      false,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_Sw2' (modeled as:'APP_Sw2.APP_RGBSM.APP') */
      false,
      /* struct element:'APP_IRAM.APP_RGBSM.APP_Sw3' (modeled as:'APP_Sw3.APP_RGBSM.APP') */
      false,
      /* struct element:'APP_IRAM.APP_RGBSM.sm' (modeled as:'sm.APP_RGBSM.APP') */
      0U,
      /* substruct: APP_IRAM.APP_RGBSM.APP_LedTimer (modeled as:'APP_LedTimer.APP_RGBSM.APP') */
      {
         /* struct element:'APP_IRAM.APP_RGBSM.APP_LedTimer.LIB_TimeInternal' (modeled as:'LIB_TimeInternal.APP_LedTimer.APP_RGBSM.APP') */
         0U
      },
      /* substruct: APP_IRAM.APP_RGBSM.APP_Rise2 (modeled as:'APP_Rise2.APP_RGBSM.APP') */
      {
         /* struct element:'APP_IRAM.APP_RGBSM.APP_Rise2.LIB_Prev' (modeled as:'LIB_Prev.APP_Rise2.APP_RGBSM.APP') */
         false,
         /* struct element:'APP_IRAM.APP_RGBSM.APP_Rise2.LIB_RiseLocal' (modeled as:'LIB_RiseLocal.APP_Rise2.APP_RGBSM.APP') */
         false
      },
      /* substruct: APP_IRAM.APP_RGBSM.APP_Rise3 (modeled as:'APP_Rise3.APP_RGBSM.APP') */
      {
         /* struct element:'APP_IRAM.APP_RGBSM.APP_Rise3.LIB_Prev' (modeled as:'LIB_Prev.APP_Rise3.APP_RGBSM.APP') */
         false,
         /* struct element:'APP_IRAM.APP_RGBSM.APP_Rise3.LIB_RiseLocal' (modeled as:'LIB_RiseLocal.APP_Rise3.APP_RGBSM.APP') */
         false
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'APP_IRAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'APP'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IFLASH'
 * model name:...................................'APP'
 * data set:.....................................'APP_EVB_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct APP_EVB APP = {
   /* substruct: APP.APP_LeverLightControl (modeled as:'APP_LeverLightControl.APP') */
   {
      /* type descriptor pointer 'APP_LEVERLIGHTS_EVB_EFLASH' for memory class substruct for 'EFLASH' */
      &APP_EFLASH.APP_LeverLightControl,
      /* type descriptor pointer 'APP_LEVERLIGHTS_EVB_IRAM' for memory class substruct for 'IRAM' */
      &APP_IRAM.APP_LeverLightControl,
      /* substruct: APP.APP_LeverLightControl.APP_FlashCounter (modeled as:'APP_FlashCounter.APP_LeverLightControl.APP') */
      {
         /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
         &APP_IRAM.APP_LeverLightControl.APP_FlashCounter
      },
      /* substruct: APP.APP_LeverLightControl.APP_LightDuty (modeled as:'APP_LightDuty.APP_LeverLightControl.APP') */
      {
         /* type descriptor pointer 'APP_LIGHTDUTYSWITCH_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverLightControl.APP_LightDuty
      }
   },
   /* substruct: APP.APP_LeverSelect (modeled as:'APP_LeverSelect.APP') */
   {
      /* type descriptor pointer 'APP_LEVERSELECTION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
      &APP_EFLASH.APP_LeverSelect,
      /* type descriptor pointer 'APP_LEVERSELECTION_EVB_IRAM' for memory class substruct for 'IRAM' */
      &APP_IRAM.APP_LeverSelect,
      /* substruct: APP.APP_LeverSelect.APP_DriveSwitchInterp (modeled as:'APP_DriveSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_DriveSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_DriveSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_DriveSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_DriveSwitchInterp.APP_SwitchTimer
         }
      },
      /* substruct: APP.APP_LeverSelect.APP_ManualSwitchInterp (modeled as:'APP_ManualSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_ManualSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_ManualSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_ManualSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_ManualSwitchInterp.APP_SwitchTimer
         }
      },
      /* substruct: APP.APP_LeverSelect.APP_MinusSwitchInterp (modeled as:'APP_MinusSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_MinusSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_MinusSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_MinusSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_MinusSwitchInterp.APP_SwitchTimer
         }
      },
      /* substruct: APP.APP_LeverSelect.APP_NeutralSwitchInterp (modeled as:'APP_NeutralSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_NeutralSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_NeutralSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_NeutralSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_NeutralSwitchInterp.APP_SwitchTimer
         }
      },
      /* substruct: APP.APP_LeverSelect.APP_ParkSwitchInterp (modeled as:'APP_ParkSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_ParkSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_ParkSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_ParkSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_ParkSwitchInterp.APP_SwitchTimer
         }
      },
      /* substruct: APP.APP_LeverSelect.APP_PlusSwitchInterp (modeled as:'APP_PlusSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_PlusSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_PlusSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_PlusSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_PlusSwitchInterp.APP_SwitchTimer
         }
      },
      /* substruct: APP.APP_LeverSelect.APP_ReverseSwitchInterp (modeled as:'APP_ReverseSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_ReverseSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_ReverseSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_ReverseSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_ReverseSwitchInterp.APP_SwitchTimer
         }
      },
      /* substruct: APP.APP_LeverSelect.APP_SportSwitchInterp (modeled as:'APP_SportSwitchInterp.APP_LeverSelect.APP') */
      {
         /* type descriptor pointer 'APP_SWITCHINTERPRETATION_EVB_EFLASH' for memory class substruct for 'EFLASH' */
         &APP_EFLASH.APP_LeverSelect.APP_SportSwitchInterp,
         /* substruct: APP.APP_LeverSelect.APP_SportSwitchInterp.APP_SwitchTimer (modeled as:'APP_SwitchTimer.APP_SportSwitchInterp.APP_LeverSelect.APP') */
         {
            /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
            &APP_IRAM.APP_LeverSelect.APP_SportSwitchInterp.APP_SwitchTimer
         }
      }
   },
   /* substruct: APP.APP_RGBSM (modeled as:'APP_RGBSM.APP') */
   {
      /* type descriptor pointer 'APP_RGBCONTROL_EVB_EFLASH' for memory class substruct for 'EFLASH' */
      &APP_EFLASH.APP_RGBSM,
      /* type descriptor pointer 'APP_RGBCONTROL_EVB_IRAM' for memory class substruct for 'IRAM' */
      &APP_IRAM.APP_RGBSM,
      /* substruct: APP.APP_RGBSM.APP_LedTimer (modeled as:'APP_LedTimer.APP_RGBSM.APP') */
      {
         /* type descriptor pointer 'LIB_TIMERUP_EVB_IRAM' for memory class substruct for 'IRAM' */
         &APP_IRAM.APP_RGBSM.APP_LedTimer
      },
      /* substruct: APP.APP_RGBSM.APP_Rise2 (modeled as:'APP_Rise2.APP_RGBSM.APP') */
      {
         /* type descriptor pointer 'LIB_RISE_EVB_IRAM' for memory class substruct for 'IRAM' */
         &APP_IRAM.APP_RGBSM.APP_Rise2
      },
      /* substruct: APP.APP_RGBSM.APP_Rise3 (modeled as:'APP_Rise3.APP_RGBSM.APP') */
      {
         /* type descriptor pointer 'LIB_RISE_EVB_IRAM' for memory class substruct for 'IRAM' */
         &APP_IRAM.APP_RGBSM.APP_Rise3
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'APP'
 ******************************************************************************/





#define _APP_LeverLightControl_REF_ (&(APP.APP_LeverLightControl))
#define _APP_LeverSelect_REF_ (&(APP.APP_LeverSelect))
#define _APP_RGBSM_REF_ (&(APP.APP_RGBSM))
#define _APP_SpeedOperand1 (APP_IRAM.APP_SpeedOperand1)
#define _APP_SpeedOperand2 (APP_IRAM.APP_SpeedOperand2)
#define _APP_SpeedSubtraction (APP_IRAM.APP_SpeedSubtraction)
#define _APP_SpeedSum (APP_IRAM.APP_SpeedSum)
#define _APP_Toggle (APP_IRAM.APP_Toggle)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'APP_EVB_APP_10ms'
 * ----------------------------------------------------------------------------
 * model name:...................................'APP_10ms'
 * memory class:.................................'ICODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */

/* public APP_10ms []  */

void APP_EVB_APP_10ms (void)
{
   /* define local message copies */
   uint16 APPInterface_APP_D10_PTB5__APP_EVB_APP_10ms;
   uint16 APPInterface_APP_D11_PTB4__APP_EVB_APP_10ms;
   uint16 APPInterface_APP_D12_PTB3__APP_EVB_APP_10ms;
   uint16 APPInterface_APP_D13_PTB2__APP_EVB_APP_10ms;
   uint16 APPInterface_APP_D8_PTD13__APP_EVB_APP_10ms;
   uint16 APPInterface_APP_D9_PTD14__APP_EVB_APP_10ms;
   struct T_LEVEROUT_EVB APPInterface_APP_LeverOut__APP_EVB_APP_10ms;
   boolean INInterface_IN_GPIOPTA10__APP_EVB_APP_10ms;
   boolean INInterface_IN_GPIOPTB6__APP_EVB_APP_10ms;
   boolean INInterface_IN_GPIOPTB7__APP_EVB_APP_10ms;
   boolean INInterface_IN_GPIOPTC4__APP_EVB_APP_10ms;
   boolean INInterface_IN_GPIOPTC5__APP_EVB_APP_10ms;
   boolean INInterface_IN_GPIOPTE0__APP_EVB_APP_10ms;
   boolean INInterface_IN_GPIOPTE9__APP_EVB_APP_10ms;
   struct T_LEVERIN_EVB INInterface_IN_LeverIn__APP_EVB_APP_10ms;
   uint16 INInterface_IN_Potentiometer_PTC14__APP_EVB_APP_10ms;
   boolean INInterface_IN_SW2_PTC12__APP_EVB_APP_10ms;
   boolean INInterface_IN_SW3_PTC13__APP_EVB_APP_10ms;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      APPInterface_APP_D10_PTB5__APP_EVB_APP_10ms = APPInterface_APP_D10_PTB5;
      APPInterface_APP_D11_PTB4__APP_EVB_APP_10ms = APPInterface_APP_D11_PTB4;
      APPInterface_APP_D12_PTB3__APP_EVB_APP_10ms = APPInterface_APP_D12_PTB3;
      APPInterface_APP_D13_PTB2__APP_EVB_APP_10ms = APPInterface_APP_D13_PTB2;
      APPInterface_APP_D8_PTD13__APP_EVB_APP_10ms = APPInterface_APP_D8_PTD13;
      APPInterface_APP_D9_PTD14__APP_EVB_APP_10ms = APPInterface_APP_D9_PTD14;
      INInterface_IN_GPIOPTA10__APP_EVB_APP_10ms = INInterface_IN_GPIOPTA10;
      INInterface_IN_GPIOPTB6__APP_EVB_APP_10ms = INInterface_IN_GPIOPTB6;
      INInterface_IN_GPIOPTB7__APP_EVB_APP_10ms = INInterface_IN_GPIOPTB7;
      INInterface_IN_GPIOPTC4__APP_EVB_APP_10ms = INInterface_IN_GPIOPTC4;
      INInterface_IN_GPIOPTC5__APP_EVB_APP_10ms = INInterface_IN_GPIOPTC5;
      INInterface_IN_GPIOPTE0__APP_EVB_APP_10ms = INInterface_IN_GPIOPTE0;
      INInterface_IN_GPIOPTE9__APP_EVB_APP_10ms = INInterface_IN_GPIOPTE9;
      INInterface_IN_Potentiometer_PTC14__APP_EVB_APP_10ms = INInterface_IN_Potentiometer_PTC14;
      INInterface_IN_SW2_PTC12__APP_EVB_APP_10ms = INInterface_IN_SW2_PTC12;
      INInterface_IN_SW3_PTC13__APP_EVB_APP_10ms = INInterface_IN_SW3_PTC13;
      memcpy(&(APPInterface_APP_LeverOut__APP_EVB_APP_10ms), &(APPInterface_APP_LeverOut), sizeof(APPInterface_APP_LeverOut__APP_EVB_APP_10ms));
      memcpy(&(INInterface_IN_LeverIn__APP_EVB_APP_10ms), &(INInterface_IN_LeverIn), sizeof(INInterface_IN_LeverIn__APP_EVB_APP_10ms));
      EnableAllInterrupts();
   }
   /* APP_10ms: source line #56:  APPInterface.APP_LeverOut = APP_LeverSelect.APP_LeverSelect(INInterface.IN_GPIOPTB6, INInterface.IN_GPIOPTB7, INInterface.IN_SW2_PTC12, INInterface.IN_SW3_PTC13, INInterface.IN_GPIOPTE0, INInterface.IN_GPIOPTE9, INInterface.IN_GPIOPTC5, INInterface.IN_GPIOPTC4, INInterface.IN_Potentiometer_PTC14);  */
   memcpy(&APPInterface_APP_LeverOut__APP_EVB_APP_10ms , APP_LEVERSELECTION_EVB_APP_LeverSelect(_APP_LeverSelect_REF_, INInterface_IN_GPIOPTB6__APP_EVB_APP_10ms, INInterface_IN_GPIOPTB7__APP_EVB_APP_10ms, INInterface_IN_SW2_PTC12__APP_EVB_APP_10ms, INInterface_IN_SW3_PTC13__APP_EVB_APP_10ms, INInterface_IN_GPIOPTE0__APP_EVB_APP_10ms, INInterface_IN_GPIOPTE9__APP_EVB_APP_10ms, INInterface_IN_GPIOPTC5__APP_EVB_APP_10ms, INInterface_IN_GPIOPTC4__APP_EVB_APP_10ms, INInterface_IN_Potentiometer_PTC14__APP_EVB_APP_10ms) , sizeof(struct T_LEVEROUT_EVB));
   /* APP_10ms: source line #57:  APPInterface.APP_LeverOut.LVR_TestResponse = APP_SanityCheck.SanityReturn(INInterface.IN_LeverIn.TCM_TestData1, INInterface.IN_LeverIn.TCM_TestData2);  */
   /* assignment to APPInterface_APP_LeverOut.LVR_TestResponse: min=0, max=255, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
   APPInterface_APP_LeverOut__APP_EVB_APP_10ms.LVR_TestResponse
      = APP_SANITY_EVB_SanityReturn(INInterface_IN_LeverIn__APP_EVB_APP_10ms.TCM_TestData1, INInterface_IN_LeverIn__APP_EVB_APP_10ms.TCM_TestData2);
   /* APP_10ms: source line #58:  APP_LeverLightControl.APP_LightCtrl(INInterface.IN_LeverIn, INInterface.IN_GPIOPTA10)  */
   APP_LEVERLIGHTS_EVB_APP_LightCtrl(_APP_LeverLightControl_REF_, &INInterface_IN_LeverIn__APP_EVB_APP_10ms, INInterface_IN_GPIOPTA10__APP_EVB_APP_10ms);
   /* APP_10ms: source line #59:  APPInterface.APP_D8_PTD13 = APP_LeverLightControl.APP_ParkDuty;  */
   /* assignment to APPInterface_APP_D8_PTD13: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_D8_PTD13__APP_EVB_APP_10ms = APP_IRAM.APP_LeverLightControl.APP_ParkDuty;
   /* APP_10ms: source line #60:  APPInterface.APP_D9_PTD14 = APP_LeverLightControl.APP_ReverseDuty;  */
   /* assignment to APPInterface_APP_D9_PTD14: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_D9_PTD14__APP_EVB_APP_10ms = APP_IRAM.APP_LeverLightControl.APP_ReverseDuty;
   /* APP_10ms: source line #61:  APPInterface.APP_D10_PTB5 = APP_LeverLightControl.APP_NeutralDuty;  */
   /* assignment to APPInterface_APP_D10_PTB5: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_D10_PTB5__APP_EVB_APP_10ms = APP_IRAM.APP_LeverLightControl.APP_NeutralDuty;
   /* APP_10ms: source line #62:  APPInterface.APP_D11_PTB4 = APP_LeverLightControl.APP_DriveDuty;  */
   /* assignment to APPInterface_APP_D11_PTB4: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_D11_PTB4__APP_EVB_APP_10ms = APP_IRAM.APP_LeverLightControl.APP_DriveDuty;
   /* APP_10ms: source line #63:  APPInterface.APP_D12_PTB3 = APP_LeverLightControl.APP_SportDuty;  */
   /* assignment to APPInterface_APP_D12_PTB3: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_D12_PTB3__APP_EVB_APP_10ms = APP_IRAM.APP_LeverLightControl.APP_SportDuty;
   /* APP_10ms: source line #64:  APPInterface.APP_D13_PTB2 = APP_LeverLightControl.APP_ManualDuty;  */
   /* assignment to APPInterface_APP_D13_PTB2: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_D13_PTB2__APP_EVB_APP_10ms = APP_IRAM.APP_LeverLightControl.APP_ManualDuty;
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      APPInterface_APP_D10_PTB5 = APPInterface_APP_D10_PTB5__APP_EVB_APP_10ms;
      APPInterface_APP_D11_PTB4 = APPInterface_APP_D11_PTB4__APP_EVB_APP_10ms;
      APPInterface_APP_D12_PTB3 = APPInterface_APP_D12_PTB3__APP_EVB_APP_10ms;
      APPInterface_APP_D13_PTB2 = APPInterface_APP_D13_PTB2__APP_EVB_APP_10ms;
      APPInterface_APP_D8_PTD13 = APPInterface_APP_D8_PTD13__APP_EVB_APP_10ms;
      APPInterface_APP_D9_PTD14 = APPInterface_APP_D9_PTD14__APP_EVB_APP_10ms;
      memcpy(&(APPInterface_APP_LeverOut), &(APPInterface_APP_LeverOut__APP_EVB_APP_10ms), sizeof(APPInterface_APP_LeverOut));
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'APP_EVB_APP_10ms'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'APP_EVB_APP_1ms'
 * ----------------------------------------------------------------------------
 * model name:...................................'APP_1ms'
 * memory class:.................................'ICODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */

/* public APP_1ms []  */

void APP_EVB_APP_1ms (void)
{
   /* define local message copies */
   uint16 APPInterface_APP_BlueLED__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D14_PTA9__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D15_PTA8__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D16_PTE12__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D17_PTD17__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D18_PTC9__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D19_PTC8__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D20_PTD8__APP_EVB_APP_1ms;
   boolean APPInterface_APP_D21_PTD9__APP_EVB_APP_1ms;
   boolean APPInterface_APP_GPIOPTD0__APP_EVB_APP_1ms;
   boolean APPInterface_APP_GPIOPTD2__APP_EVB_APP_1ms;
   uint16 APPInterface_APP_GreenLED__APP_EVB_APP_1ms;
   uint16 APPInterface_APP_RedLED__APP_EVB_APP_1ms;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D6_IC_PTC12__APP_EVB_APP_1ms;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D7_IC_PTC13__APP_EVB_APP_1ms;
   uint16 INInterface_IN_Potentiometer_PTC14__APP_EVB_APP_1ms;
   boolean INInterface_IN_SW2_PTC12__APP_EVB_APP_1ms;
   boolean INInterface_IN_SW3_PTC13__APP_EVB_APP_1ms;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      APPInterface_APP_BlueLED__APP_EVB_APP_1ms = APPInterface_APP_BlueLED;
      APPInterface_APP_D14_PTA9__APP_EVB_APP_1ms = APPInterface_APP_D14_PTA9;
      APPInterface_APP_D15_PTA8__APP_EVB_APP_1ms = APPInterface_APP_D15_PTA8;
      APPInterface_APP_D16_PTE12__APP_EVB_APP_1ms = APPInterface_APP_D16_PTE12;
      APPInterface_APP_D17_PTD17__APP_EVB_APP_1ms = APPInterface_APP_D17_PTD17;
      APPInterface_APP_D18_PTC9__APP_EVB_APP_1ms = APPInterface_APP_D18_PTC9;
      APPInterface_APP_D19_PTC8__APP_EVB_APP_1ms = APPInterface_APP_D19_PTC8;
      APPInterface_APP_D20_PTD8__APP_EVB_APP_1ms = APPInterface_APP_D20_PTD8;
      APPInterface_APP_D21_PTD9__APP_EVB_APP_1ms = APPInterface_APP_D21_PTD9;
      APPInterface_APP_GPIOPTD0__APP_EVB_APP_1ms = APPInterface_APP_GPIOPTD0;
      APPInterface_APP_GPIOPTD2__APP_EVB_APP_1ms = APPInterface_APP_GPIOPTD2;
      APPInterface_APP_GreenLED__APP_EVB_APP_1ms = APPInterface_APP_GreenLED;
      APPInterface_APP_RedLED__APP_EVB_APP_1ms = APPInterface_APP_RedLED;
      INInterface_IN_Potentiometer_PTC14__APP_EVB_APP_1ms = INInterface_IN_Potentiometer_PTC14;
      INInterface_IN_SW2_PTC12__APP_EVB_APP_1ms = INInterface_IN_SW2_PTC12;
      INInterface_IN_SW3_PTC13__APP_EVB_APP_1ms = INInterface_IN_SW3_PTC13;
      memcpy(&(INInterface_IN_D6_IC_PTC12__APP_EVB_APP_1ms), &(INInterface_IN_D6_IC_PTC12), sizeof(INInterface_IN_D6_IC_PTC12__APP_EVB_APP_1ms));
      memcpy(&(INInterface_IN_D7_IC_PTC13__APP_EVB_APP_1ms), &(INInterface_IN_D7_IC_PTC13), sizeof(INInterface_IN_D7_IC_PTC13__APP_EVB_APP_1ms));
      EnableAllInterrupts();
   }
   /* APP_1ms: source line #23:  APP_RGBSM.APP_Sw2 = INInterface.IN_SW2_PTC12;  */
   APP_IRAM.APP_RGBSM.APP_Sw2 = INInterface_IN_SW2_PTC12__APP_EVB_APP_1ms;
   /* APP_1ms: source line #24:  APP_RGBSM.APP_Sw3 = INInterface.IN_SW3_PTC13;  */
   APP_IRAM.APP_RGBSM.APP_Sw3 = INInterface_IN_SW3_PTC13__APP_EVB_APP_1ms;
   /* APP_1ms: source line #25:  APP_RGBSM.APP_Pot = INInterface.IN_Potentiometer_PTC14;  */
   /* assignment to APP_RGBSM.APP_Pot: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APP_IRAM.APP_RGBSM.APP_Pot = INInterface_IN_Potentiometer_PTC14__APP_EVB_APP_1ms;
   /* APP_1ms: source line #26:  APP_RGBSM.APP_RGBStateMachineTrig()  */
   APP_RGBCONTROL_EVB_APP_RGBStateMachineTrig(_APP_RGBSM_REF_);
   /* APP_1ms: source line #27:  APPInterface.APP_RedLED = (100.0 - APP_RGBSM.APP_RedDuty);  */
   /* assignment to APPInterface_APP_RedLED: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_RedLED__APP_EVB_APP_1ms
      = ((uint16)((uint16)10000U) - (APP_IRAM.APP_RGBSM.APP_RedDuty));
   /* APP_1ms: source line #28:  APPInterface.APP_GreenLED = (100.0 - APP_RGBSM.APP_GreenDuty);  */
   /* assignment to APPInterface_APP_GreenLED: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_GreenLED__APP_EVB_APP_1ms
      = ((uint16)((uint16)10000U) - (APP_IRAM.APP_RGBSM.APP_GreenDuty));
   /* APP_1ms: source line #29:  APPInterface.APP_BlueLED = (100.0 - APP_RGBSM.APP_BlueDuty);  */
   /* assignment to APPInterface_APP_BlueLED: min=0, max=10000, hex=100phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   APPInterface_APP_BlueLED__APP_EVB_APP_1ms
      = ((uint16)((uint16)10000U) - (APP_IRAM.APP_RGBSM.APP_BlueDuty));
   /* APP_1ms: source line #32:  APP_Toggle = (!APP_Toggle);  */
   _APP_Toggle = !_APP_Toggle;
   /* APP_1ms: source line #33:  APPInterface.APP_D14_PTA9 = APP_Toggle;  */
   APPInterface_APP_D14_PTA9__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #34:  APPInterface.APP_D15_PTA8 = APP_Toggle;  */
   APPInterface_APP_D15_PTA8__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #35:  APPInterface.APP_D16_PTE12 = APP_Toggle;  */
   APPInterface_APP_D16_PTE12__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #36:  APPInterface.APP_D17_PTD17 = APP_Toggle;  */
   APPInterface_APP_D17_PTD17__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #37:  APPInterface.APP_D18_PTC9 = APP_Toggle;  */
   APPInterface_APP_D18_PTC9__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #38:  APPInterface.APP_D19_PTC8 = APP_Toggle;  */
   APPInterface_APP_D19_PTC8__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #39:  APPInterface.APP_D20_PTD8 = APP_Toggle;  */
   APPInterface_APP_D20_PTD8__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #40:  APPInterface.APP_D21_PTD9 = APP_Toggle;  */
   APPInterface_APP_D21_PTD9__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #41:  APPInterface.APP_GPIOPTD2 = APP_Toggle;  */
   APPInterface_APP_GPIOPTD2__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #42:  APPInterface.APP_GPIOPTD0 = APP_Toggle;  */
   APPInterface_APP_GPIOPTD0__APP_EVB_APP_1ms = _APP_Toggle;
   /* APP_1ms: source line #45:  APP_SpeedOperand1 = INInterface.IN_D6_IC_PTC12.IN_Speed;  */
   /* assignment to APP_SpeedOperand1: min=-32768, max=32767, hex=1phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_SpeedOperand1 = INInterface_IN_D6_IC_PTC12__APP_EVB_APP_1ms.IN_Speed;
   /* APP_1ms: source line #46:  APP_SpeedOperand2 = INInterface.IN_D7_IC_PTC13.IN_Speed;  */
   /* assignment to APP_SpeedOperand2: min=-32768, max=32767, hex=1phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_SpeedOperand2 = INInterface_IN_D7_IC_PTC13__APP_EVB_APP_1ms.IN_Speed;
   /* APP_1ms: source line #47:  APP_SpeedSum = (APP_SpeedOperand1 + APP_SpeedOperand2);  */
   /* assignment to APP_SpeedSum: min=-32768, max=32767, hex=1phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_SpeedSum
      = (sint16)ADDLIM_S16S16_S16(_APP_SpeedOperand1,_APP_SpeedOperand2);
   /* APP_1ms: source line #48:  APP_SpeedSubtraction = (APP_SpeedOperand1 - APP_SpeedOperand2);  */
   /* assignment to APP_SpeedSubtraction: min=-32768, max=32767, hex=1phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   _APP_SpeedSubtraction
      = (sint16)SUBLIM_S16S16_S16(_APP_SpeedOperand1,_APP_SpeedOperand2);
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      APPInterface_APP_BlueLED = APPInterface_APP_BlueLED__APP_EVB_APP_1ms;
      APPInterface_APP_D14_PTA9 = APPInterface_APP_D14_PTA9__APP_EVB_APP_1ms;
      APPInterface_APP_D15_PTA8 = APPInterface_APP_D15_PTA8__APP_EVB_APP_1ms;
      APPInterface_APP_D16_PTE12 = APPInterface_APP_D16_PTE12__APP_EVB_APP_1ms;
      APPInterface_APP_D17_PTD17 = APPInterface_APP_D17_PTD17__APP_EVB_APP_1ms;
      APPInterface_APP_D18_PTC9 = APPInterface_APP_D18_PTC9__APP_EVB_APP_1ms;
      APPInterface_APP_D19_PTC8 = APPInterface_APP_D19_PTC8__APP_EVB_APP_1ms;
      APPInterface_APP_D20_PTD8 = APPInterface_APP_D20_PTD8__APP_EVB_APP_1ms;
      APPInterface_APP_D21_PTD9 = APPInterface_APP_D21_PTD9__APP_EVB_APP_1ms;
      APPInterface_APP_GPIOPTD0 = APPInterface_APP_GPIOPTD0__APP_EVB_APP_1ms;
      APPInterface_APP_GPIOPTD2 = APPInterface_APP_GPIOPTD2__APP_EVB_APP_1ms;
      APPInterface_APP_GreenLED = APPInterface_APP_GreenLED__APP_EVB_APP_1ms;
      APPInterface_APP_RedLED = APPInterface_APP_RedLED__APP_EVB_APP_1ms;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'APP_EVB_APP_1ms'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



