#ifndef ESDL_MESSAGECOPY_H
#define ESDL_MESSAGECOPY_H
/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................Operating system interface for message optimization
 * REPRESENTATION:..............-
 * DESCRIPTION:
 *    contains API for message copy functions, which will be called from
 *    operating system tasks
 ******************************************************************************/

#include "esdl.h"

/* ACCESS MACROS FOR MESSAGES */

/* DECLARATIONS OF MESSAGE COPIES */

/* DECLARATIONS OF SEND/RECIVE FUNCTIONS */
#endif /* ESDL_MESSAGECOPY_H */
