/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.IN.IN_CANConfig
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_IN_CANCONFIG_EVB_H_
#define _ASD_IN_CANCONFIG_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"


/* component structure for class IN_CANCONFIG_EVB intentionally not created   */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........................IN_CANCONFIG_EVB */
#define _IN_CANCONFIG_EVB_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class IN_CANCONFIG_EVB
 ******************************************************************************/
extern void IN_CANCONFIG_EVB_initCANChannel (
   /* IN    */ uint8  IN_Channel,
   /* IN    */ uint16 IN_Baud
   );
extern void IN_CANCONFIG_EVB_startCANChannel (/* IN    */ uint8 IN_Channel);



#endif /* _ASD_IN_CANCONFIG_EVB_H_ */
