/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.IN.IN_InputCaptureIn
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_IN_INPUTCAPTUREIN_EVB_H_
#define _ASD_IN_INPUTCAPTUREIN_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"
#include "T_InputCapture_EVB.h"


/* component structure for class IN_INPUTCAPTUREIN_EVB intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......................IN_INPUTCAPTUREIN_EVB */
#define _IN_INPUTCAPTUREIN_EVB_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class IN_INPUTCAPTUREIN_EVB
 ******************************************************************************/
extern struct T_INPUTCAPTURE_EVB * IN_INPUTCAPTUREIN_EVB_getSpeedIn (
   /* IN    */ uint8  port,
   /* IN    */ uint32 timeout,
   /* IN    */ uint8  ppr
   );



#endif /* _ASD_IN_INPUTCAPTUREIN_EVB_H_ */
