/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.IN.IN_Main
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_IN_MAIN_EVB_H_
#define _ASD_IN_MAIN_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"
#include "IN_AnaIn_EVB.h"
#include "IN_CANConfig_EVB.h"
#include "IN_CANMessageInit_EVB.h"
#include "IN_CANRxTCM_EVB.h"
#include "IN_DigitalIn_EVB.h"
#include "IN_InputCaptureIn_EVB.h"
#include "LIB_4BitCountTest_EVB.h"
#include "LIB_CANStatus_EVB.h"
#include "T_CANTCMLever_EVB.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'IN_MAIN_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'EFLASH'
 * ---------------------------------------------------------------------------*/
struct IN_MAIN_EVB_EFLASH_SUBSTRUCT {
   uint32 IN_CANRXTCMID;	/* min=0, max=4294967295, esdl_ident, limit=yes */
   uint32 IN_D0_IC_PTA2_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_D1_IC_PTA3_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_D2_IC_PTB10_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_D3_IC_PTB11_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_D4_IC_PTC10_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_D5_IC_PTC11_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_D6_IC_PTC12_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_D7_IC_PTC13_TIMEOUT;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint16 IN_CANRXTCMTIMEOUT;	/* min=0.0, max=65.53, esdl_f0_001, limit=yes */
   uint8 IN_CANRXTCMCHAN;	/* min=0, max=3, esdl_ident, limit=yes */
   uint8 IN_CANRXTCMLEN;	/* min=1, max=8, esdl_ident, limit=yes */
   uint8 IN_D0_IC_PTA2_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   uint8 IN_D1_IC_PTA3_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   uint8 IN_D2_IC_PTB10_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   uint8 IN_D3_IC_PTB11_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   uint8 IN_D4_IC_PTC10_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   uint8 IN_D5_IC_PTC11_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   uint8 IN_D6_IC_PTC12_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   uint8 IN_D7_IC_PTC13_PPR;	/* min=1, max=255, esdl_ident, limit=yes */
   struct LIB_4BITCOUNTTEST_EVB_EFLASH_SUBSTRUCT IN_CANTxTCMCountTest;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'IN_MAIN_EVB'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'IN_MAIN_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IRAM'
 * ---------------------------------------------------------------------------*/
struct IN_MAIN_EVB_IRAM_SUBSTRUCT {
   boolean IN_CANRxNewData;	/* min=0, max=1, Identity, limit=yes */
   uint8 IN_CANRxTCMStatus;	/* min=0, max=6, H_Status_tab_verb, limit=yes */
   boolean IN_RxTCMChkOkay;	/* min=0, max=1, Identity, limit=yes */
   uint8 IN_RxTCMCounter;	/* min=0, max=15, esdl_ident, limit=yes */
   boolean IN_RxTCMCounterOkay;	/* min=0, max=1, Identity, limit=yes */
   sint8 IN_RxTCMHandle;	/* min=-128, max=127, esdl_ident, limit=yes */
   struct T_CANTCMLEVER_EVB IN_CANTCMData;
   struct LIB_CANSTATUS_EVB_IRAM_SUBSTRUCT IN_CANRxTCMStatCheck;
   struct LIB_4BITCOUNTTEST_EVB_IRAM_SUBSTRUCT IN_CANTxTCMCountTest;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'IN_MAIN_EVB'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'IN_MAIN_EVB'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IFLASH'
 * ---------------------------------------------------------------------------*/
struct IN_MAIN_EVB {
   struct LIB_CANSTATUS_EVB IN_CANRxTCMStatCheck;
   struct LIB_4BITCOUNTTEST_EVB IN_CANTxTCMCountTest;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'IN_MAIN_EVB'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................................IN_MAIN_EVB */
#define _IN_MAIN_EVB_TYPE_DEF_




/* forward declaration of substruct variable 'IN_Main_EFLASH' */
/* containing 'EFLASH' memory class tree */
extern struct IN_MAIN_EVB_EFLASH_SUBSTRUCT __attribute__ ((section (".par_ram"))) IN_Main_EFLASH;

/* forward declaration of substruct variable 'IN_Main_IRAM' */
/* containing 'IRAM' memory class tree */
extern struct IN_MAIN_EVB_IRAM_SUBSTRUCT IN_Main_IRAM;

/* forward declaration of component variable 'IN_Main' */
/* containing 'IFLASH' memory class tree */
extern struct IN_MAIN_EVB IN_Main;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module IN_MAIN_EVB
 ******************************************************************************/
extern void IN_MAIN_EVB_IN_Init (void);
extern void IN_MAIN_EVB_IN_dT (void);



#endif /* _ASD_IN_MAIN_EVB_H_ */
