/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.IN.IN_Main
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "IN_Main_EVB.h"
#include "INInterface_EVB.h"
#include "S32K144Build_ARM_ArithmeticServices_EVB.h"
#include "T_InputCapture_EVB.h"
#include "T_LeverIn_EVB.h"


/******************************************************************************
 * BEGIN: Generation Information
 *-----------------------------------------------------------------------------
 * Component:................Module
 * Name:....................."IN_Main"
 * Implementation:..........."EVB"
 * Dataset:.................."esdl_Data_Default"
 * Specification:............ESDL
 * Version:..................<empty String>
 * Repository Path:..........<empty String>
 * Library Path:............."\ascet\IN"
 *-----------------------------------------------------------------------------
 * Project Name:............."S32K144Build_ARM_ArithmeticServices"
 * Project Library Path:....."\_project\"
 *-----------------------------------------------------------------------------
 * Generation Date:..........02/12/2020
 * Generation Time:..........11:47:50
 *-----------------------------------------------------------------------------
 * ASCET Version:............V7.5.0
 * ASCET-MD Version:.........V7.5.0
 * ASCET-RP Version:.........not installed
 * ASCET-SE Version:.........V6.4.4-0197
 *-----------------------------------------------------------------------------
 * END: Generation Information
 ******************************************************************************/



/******************************************************************************
 * BEGIN: Project Options "Build"/"Code"
 *-----------------------------------------------------------------------------
 *    Build
 *-----------------------------------------------------------------------------
 * Code Generator:...........Object Based Controller Implementation
 * Compiler:.................Virtual ESDL Compiler
 * Operating System:.........GENERIC_OSEK
 * Target:...................ANSI-C for ESDL
 *-----------------------------------------------------------------------------
 *    Code
 *-----------------------------------------------------------------------------
 * Add Comment with Generation Information for each Component [true]: true
 * Add Comment with Implementation Information for each Assignment Statement [true]: true
 * Add Comment with Specification Source for each Statement [true]:..true
 * Add parenthesis for readability [true]:...........................true
 * Allow References without Init Value [false]:......................false
 * Casting [MISRA]:..................................................MISRA
 * Force Parenthesis for Binary Logical Operators [true]:............true
 * Generate Define Directives for Enum Values [false]:...............false
 * Prefix for Component Names [<empty String>]:......................<empty String>
 * Protected against division by zero [true]:........................true
 * Protected Division against Signed Overflow [true]:................true
 * Protected Vector Indices [true]:..................................true
 * Result on Division by Zero [numerator]:...........................numerator
 * Use Redundant Data Storage [true]:................................true
 *-----------------------------------------------------------------------------
 *    Code.Compiler
 *-----------------------------------------------------------------------------
 * Division truncation direction [Zero (T-division)]:................Zero (T-division)
 * Inline directive [<empty String>]:................................<empty String>
 * Integer Bit Size [32]:............................................32
 * Private directive [<empty String>]:...............................<empty String>
 * Public directive [<empty String>]:................................<empty String>
 *-----------------------------------------------------------------------------
 *    Code.FixedPoint
 *-----------------------------------------------------------------------------
 * Allow Double bit Size for Division Numerators [true]:.............true
 * Arithmetic Service Set [<None>]:..................................example
 * Generate Float Limiter on Assignment [false]:.....................false
 * Generate Round Operation on float to integer Assignment [true]:...true
 * Maximum bit Length (int) [32]:....................................32
 * New Behaviour for Discrete Types [true]:..........................true
 * Temp Vars always 32 bit (integer) [false]:........................false
 * Use power of 2 approximations of literals [false]:................true
 * Use SHIFT Operation on Signed Values instead of DIV Operation [false]: false
 * Use SHIFT Operation on Signed Values instead of MUL Operation [false]: false
 *-----------------------------------------------------------------------------
 *    Code.Optimizations
 *-----------------------------------------------------------------------------
 * Auto-inline private methods (Smaller code-size - may be changed locally) [false]: false
 * Common Subexpression Elimination [false]:.........................true
 * Dead Code Elimination [Comment]:..................................Comment
 * Disable BDE Temp Variable Generation [false]:.....................true
 * Generate well-formed switch [true]:...............................true
 * Hierarchical Code-Generation (may be changed locally) [false]:....false
 * Initialise history variable with zero [false]:....................false
 * Optimize Direct Access Methods (Multiple Levels) [false]:.........true
 * Optimize Direct Access Methods (One Level) [false]:...............true
 * Optimize Static Actions (Restricted Modelling) [true]:............false
 * Outline Generated Methods (may be changed locally) [false]:.......false
 *-----------------------------------------------------------------------------
 *    Code.Production
 *-----------------------------------------------------------------------------
 * Add Implementation Definitions [true]:............................true
 * Generate Access Methods for dT (Alternative: use OS dT directly) [true]: false
 * Generate Data Structures [USELOCAL]:..............................USELOCAL
 * Generate Map File [true]:.........................................false
 * Generate OS Configuration [true]:.................................true
 * Use OID for Generation of Component Names [false]:................false
 *-----------------------------------------------------------------------------
 *    Station.Build
 *-----------------------------------------------------------------------------
 * Use Customized Data Type Names [false]:...........................true
 *-----------------------------------------------------------------------------
 *    TargetSettings.G_ANSI.Build
 *-----------------------------------------------------------------------------
 * Compile Unused Data [false]:......................................false
 * Cont Implementation Type [SINGLE]:................................SINGLE
 * Force no self pointer optimization [false]:.......................false
 * Function Name of memcpy [memcpy]:.................................memcpy
 * Generate define for constants [false]:............................false
 * Generate Method Body [Use Component Settings]:....................Use Component Settings
 * Generating Access Macros [true]:..................................true
 * Generating Access Macros for Messages [false]:....................false
 * Generating Message Copy [true]:...................................true
 * Generating SCOOP-IX [false]:......................................false
 * Matrix Orientation [columnMajor]:.................................columnMajor
 * Number of dimensions for fixed matrixes [1D]:.....................1D
 * Optimize Unused Code [false]:.....................................true
 * Place Array/Matrix reference structure of Parameters on the Stack [false]: false
 * Place Array/Matrix reference structure of Variables on the Stack [false]: false
 * Resolve System Constants [compileTime]:...........................compileTime
 * Using External Build Tool [false]:................................false
 * Variant Coded Data Structures [false]:............................false
 *-----------------------------------------------------------------------------
 * END: Project Options "Build"/"Code"
 ******************************************************************************/


/******************************************************************************
 * BEGIN: ASCET-SE AddOn Options
 * ----------------------------------------------------------------------------
 *     Code
 * ----------------------------------------------------------------------------
 * checkMemSectionVolatility [true]:.................................false
 * checkMultipleSend [false]:........................................false
 * distribVarMemClass ["DISTRRAM"]:.................................."DISTRRAM"
 * genAlwaysInitValues [false]:......................................true
 * genLogicElementsAs [PACKED_BITFIELD]:.............................PACKED_BITFIELD
 * genObjList [false]:...............................................false
 * implInfoComments [true]:..........................................true
 * initTaskMemClass ["ASD_INIT_TASK_MEM"]:..........................."ASD_INIT_TASK_MEM"
 * isrMemClass ["ASD_ISR_MEM"]:......................................"ASD_ISR_MEM"
 * mainMemClass ["ASD_EXT_CODE_MEM"]:................................"ASD_EXT_CODE_MEM"
 * paramAsSysConst [false]:..........................................false
 * pragmaMemClassAtDecl [false]:.....................................false
 * pragmaMemClassEnabled [true]:.....................................true
 * referenceMemClass ["REFRAM"]:....................................."REFRAM"
 * shortNames [false]:...............................................false
 * taskMemClass ["ASD_TASK_MEM"]:...................................."CODE"
 * virtualParameterMemClass ["VIRT_PARAM"]:.........................."VIRT_PARAM"
 * ----------------------------------------------------------------------------
 *     Code.Appearance
 * ----------------------------------------------------------------------------
 * braceLineFeed [true]:.............................................true
 * genDate [<undef>]:................................................<undef>
 * genTime [<undef>]:................................................<undef>
 * generateSignatureDecorationComments [true]:.......................true
 * lineFeedPosition [LEFT]:..........................................LEFT
 * maxIdentLength [0]:...............................................40
 * maxRightLength [60]:..............................................60
 * minLeftLength [8]:................................................8
 * preventIndentStructInit [true]:...................................true
 * ----------------------------------------------------------------------------
 *     OS
 * ----------------------------------------------------------------------------
 * MemAllocKeyword_ShortnameAndAlignment [true]:.....................true
 * Os-Config-C_gen_declaration_alarms [false]:.......................false
 * Os-Config-C_gen_declaration_appmodes [false]:.....................false
 * Os-Config-C_gen_dt_calc [false]:..................................true
 * Os-Config-C_gen_initCOM [false]:..................................false
 * Os-Config-C_gen_inittask [false]:.................................false
 * Os-Config-C_gen_main [false]:.....................................false
 * Os-Config-C_gen_process_container [false]:........................true
 * Os-Config-C_gen_startuphook [false]:..............................true
 * asd_exclusive_area ["ASD_EXCLUSIVE_AREA"]:........................"ASCET_exclusive_area"
 * messageDoInit [false]:............................................true
 * messageExternalMessageCopies [false]:.............................false
 * messageGenOSEKDeclarations [true]:................................false
 * messageIgnoreUsageInInitTask [false]:.............................false
 * messageOverloadInitValues [<undef>]:..............................<undef>
 * messageUsageVariant [OPT_COPY]:...................................NON_OPT_COPY
 * modularMessageUse [false]:........................................false
 * osAppModePattern ["%name%"]:......................................"appmode_%name%"
 * osStartupFunction [<undef>]:......................................<undef>
 * ----------------------------------------------------------------------------
 *     OS.OIL
 * ----------------------------------------------------------------------------
 * OIL-COOP-RESOURCE-name ["ASD_Cooperative_Res"]:..................."ASD_Cooperative_Res"
 * OIL-outputFile ["temp.oil"]:......................................"temp.oil"
 * ----------------------------------------------------------------------------
 *     SERAP
 * ----------------------------------------------------------------------------
 * SERAPRefPageMemoryClass ["SERAP_REF"]:............................"SERAP_REF"
 * SERAPWorkPageMemoryClass ["SERAP_WORK"]:.........................."SERAP_WORK"
 * serap [false]:....................................................false
 * serapEmbedded [true]:.............................................true
 * ----------------------------------------------------------------------------
 *     Virtual Address Tables
 * ----------------------------------------------------------------------------
 * addressTableMemoryClass ["VATROM"]:..............................."VATROM"
 * ----------------------------------------------------------------------------
 * END: ASCET-SE AddOn Options
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'IN_Main_EFLASH'
 * ----------------------------------------------------------------------------
 * memory class:.................................'EFLASH'
 * model name:...................................'IN_Main'
 * data set:.....................................'IN_MAIN_EVB_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct IN_MAIN_EVB_EFLASH_SUBSTRUCT __attribute__ ((section (".par_ram"))) IN_Main_EFLASH = {
   /* struct element:'IN_Main_EFLASH.IN_CANRXTCMID' (modeled as:'IN_CANRXTCMID.IN_Main') */
   1041U,
   /* struct element:'IN_Main_EFLASH.IN_D0_IC_PTA2_TIMEOUT' (modeled as:'IN_D0_IC_PTA2_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_D1_IC_PTA3_TIMEOUT' (modeled as:'IN_D1_IC_PTA3_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_D2_IC_PTB10_TIMEOUT' (modeled as:'IN_D2_IC_PTB10_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_D3_IC_PTB11_TIMEOUT' (modeled as:'IN_D3_IC_PTB11_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_D4_IC_PTC10_TIMEOUT' (modeled as:'IN_D4_IC_PTC10_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_D5_IC_PTC11_TIMEOUT' (modeled as:'IN_D5_IC_PTC11_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_D6_IC_PTC12_TIMEOUT' (modeled as:'IN_D6_IC_PTC12_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_D7_IC_PTC13_TIMEOUT' (modeled as:'IN_D7_IC_PTC13_TIMEOUT.IN_Main') */
   1000000U,
   /* struct element:'IN_Main_EFLASH.IN_CANRXTCMTIMEOUT' (modeled as:'IN_CANRXTCMTIMEOUT.IN_Main') */
   250U,
   /* struct element:'IN_Main_EFLASH.IN_CANRXTCMCHAN' (modeled as:'IN_CANRXTCMCHAN.IN_Main') */
   0U,
   /* struct element:'IN_Main_EFLASH.IN_CANRXTCMLEN' (modeled as:'IN_CANRXTCMLEN.IN_Main') */
   8U,
   /* struct element:'IN_Main_EFLASH.IN_D0_IC_PTA2_PPR' (modeled as:'IN_D0_IC_PTA2_PPR.IN_Main') */
   60U,
   /* struct element:'IN_Main_EFLASH.IN_D1_IC_PTA3_PPR' (modeled as:'IN_D1_IC_PTA3_PPR.IN_Main') */
   60U,
   /* struct element:'IN_Main_EFLASH.IN_D2_IC_PTB10_PPR' (modeled as:'IN_D2_IC_PTB10_PPR.IN_Main') */
   60U,
   /* struct element:'IN_Main_EFLASH.IN_D3_IC_PTB11_PPR' (modeled as:'IN_D3_IC_PTB11_PPR.IN_Main') */
   60U,
   /* struct element:'IN_Main_EFLASH.IN_D4_IC_PTC10_PPR' (modeled as:'IN_D4_IC_PTC10_PPR.IN_Main') */
   60U,
   /* struct element:'IN_Main_EFLASH.IN_D5_IC_PTC11_PPR' (modeled as:'IN_D5_IC_PTC11_PPR.IN_Main') */
   60U,
   /* struct element:'IN_Main_EFLASH.IN_D6_IC_PTC12_PPR' (modeled as:'IN_D6_IC_PTC12_PPR.IN_Main') */
   60U,
   /* struct element:'IN_Main_EFLASH.IN_D7_IC_PTC13_PPR' (modeled as:'IN_D7_IC_PTC13_PPR.IN_Main') */
   60U,
   /* substruct: IN_Main_EFLASH.IN_CANTxTCMCountTest (modeled as:'IN_CANTxTCMCountTest.IN_Main') */
   {
      /* struct element:'IN_Main_EFLASH.IN_CANTxTCMCountTest.LIB_PASSCYCLESFAIL' (modeled as:'LIB_PASSCYCLESFAIL.IN_CANTxTCMCountTest.IN_Main') */
      2U,
      /* struct element:'IN_Main_EFLASH.IN_CANTxTCMCountTest.LIB_PASSCYCLESOKAY' (modeled as:'LIB_PASSCYCLESOKAY.IN_CANTxTCMCountTest.IN_Main') */
      3U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'IN_Main_EFLASH'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'IN_Main_IRAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IRAM'
 * model name:...................................'IN_Main'
 * data set:.....................................'IN_MAIN_EVB_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct IN_MAIN_EVB_IRAM_SUBSTRUCT IN_Main_IRAM = {
   /* struct element:'IN_Main_IRAM.IN_CANRxNewData' (modeled as:'IN_CANRxNewData.IN_Main') */
   false,
   /* struct element:'IN_Main_IRAM.IN_CANRxTCMStatus' (modeled as:'IN_CANRxTCMStatus.IN_Main') */
   0U,
   /* struct element:'IN_Main_IRAM.IN_RxTCMChkOkay' (modeled as:'IN_RxTCMChkOkay.IN_Main') */
   false,
   /* struct element:'IN_Main_IRAM.IN_RxTCMCounter' (modeled as:'IN_RxTCMCounter.IN_Main') */
   0U,
   /* struct element:'IN_Main_IRAM.IN_RxTCMCounterOkay' (modeled as:'IN_RxTCMCounterOkay.IN_Main') */
   false,
   /* struct element:'IN_Main_IRAM.IN_RxTCMHandle' (modeled as:'IN_RxTCMHandle.IN_Main') */
   -1,
   /* substruct: IN_Main_IRAM.IN_CANTCMData (modeled as:'IN_CANTCMData.IN_Main') */
   {
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_ActualGear' (modeled as:'TCM_ActualGear.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_BackLight' (modeled as:'TCM_BackLight.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_Checksum' (modeled as:'TCM_Checksum.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_ChecksumOkay' (modeled as:'TCM_ChecksumOkay.IN_CANTCMData.IN_Main') */
      false,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_Counter' (modeled as:'TCM_Counter.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_DriveLight' (modeled as:'TCM_DriveLight.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_ManualLight' (modeled as:'TCM_ManualLight.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_NeutralLight' (modeled as:'TCM_NeutralLight.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_ParkLight' (modeled as:'TCM_ParkLight.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_ReverseLight' (modeled as:'TCM_ReverseLight.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_ShiftLock' (modeled as:'TCM_ShiftLock.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_SportLight' (modeled as:'TCM_SportLight.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_TargetGear' (modeled as:'TCM_TargetGear.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_TestData1' (modeled as:'TCM_TestData1.IN_CANTCMData.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTCMData.TCM_TestData2' (modeled as:'TCM_TestData2.IN_CANTCMData.IN_Main') */
      0U
   },
   /* substruct: IN_Main_IRAM.IN_CANRxTCMStatCheck (modeled as:'IN_CANRxTCMStatCheck.IN_Main') */
   {
      /* struct element:'IN_Main_IRAM.IN_CANRxTCMStatCheck.LIB_TimeSinceLast' (modeled as:'LIB_TimeSinceLast.IN_CANRxTCMStatCheck.IN_Main') */
      0U
   },
   /* substruct: IN_Main_IRAM.IN_CANTxTCMCountTest (modeled as:'IN_CANTxTCMCountTest.IN_Main') */
   {
      /* struct element:'IN_Main_IRAM.IN_CANTxTCMCountTest.LIB_CheckOk' (modeled as:'LIB_CheckOk.IN_CANTxTCMCountTest.IN_Main') */
      false,
      /* struct element:'IN_Main_IRAM.IN_CANTxTCMCountTest.LIB_Counter' (modeled as:'LIB_Counter.IN_CANTxTCMCountTest.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTxTCMCountTest.LIB_CounterPrevious' (modeled as:'LIB_CounterPrevious.IN_CANTxTCMCountTest.IN_Main') */
      0U,
      /* struct element:'IN_Main_IRAM.IN_CANTxTCMCountTest.LIB_OkayThisCycle' (modeled as:'LIB_OkayThisCycle.IN_CANTxTCMCountTest.IN_Main') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'IN_Main_IRAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'IN_Main'
 * ----------------------------------------------------------------------------
 * memory class:.................................'IFLASH'
 * model name:...................................'IN_Main'
 * data set:.....................................'IN_MAIN_EVB_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct IN_MAIN_EVB IN_Main = {
   /* substruct: IN_Main.IN_CANRxTCMStatCheck (modeled as:'IN_CANRxTCMStatCheck.IN_Main') */
   {
      /* type descriptor pointer 'LIB_CANSTATUS_EVB_IRAM' for memory class substruct for 'IRAM' */
      &IN_Main_IRAM.IN_CANRxTCMStatCheck
   },
   /* substruct: IN_Main.IN_CANTxTCMCountTest (modeled as:'IN_CANTxTCMCountTest.IN_Main') */
   {
      /* type descriptor pointer 'LIB_4BITCOUNTTEST_EVB_EFLASH' for memory class substruct for 'EFLASH' */
      &IN_Main_EFLASH.IN_CANTxTCMCountTest,
      /* type descriptor pointer 'LIB_4BITCOUNTTEST_EVB_IRAM' for memory class substruct for 'IRAM' */
      &IN_Main_IRAM.IN_CANTxTCMCountTest
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'IN_Main'
 ******************************************************************************/





#define _IN_CANRxNewData (IN_Main_IRAM.IN_CANRxNewData)
#define _IN_CANRXTCMCHAN (IN_Main_EFLASH.IN_CANRXTCMCHAN)
#define _IN_CANRXTCMID (IN_Main_EFLASH.IN_CANRXTCMID)
#define _IN_CANRXTCMLEN (IN_Main_EFLASH.IN_CANRXTCMLEN)
#define _IN_CANRxTCMStatCheck_REF_ (&(IN_Main.IN_CANRxTCMStatCheck))
#define _IN_CANRxTCMStatus (IN_Main_IRAM.IN_CANRxTCMStatus)
#define _IN_CANRXTCMTIMEOUT (IN_Main_EFLASH.IN_CANRXTCMTIMEOUT)
#define _IN_CANTCMData (IN_Main_IRAM.IN_CANTCMData)
#define _IN_CANTCMData_REF_ (&(IN_Main_IRAM.IN_CANTCMData))
#define _IN_CANTxTCMCountTest_REF_ (&(IN_Main.IN_CANTxTCMCountTest))
#define _IN_D0_IC_PTA2_PPR (IN_Main_EFLASH.IN_D0_IC_PTA2_PPR)
#define _IN_D0_IC_PTA2_TIMEOUT (IN_Main_EFLASH.IN_D0_IC_PTA2_TIMEOUT)
#define _IN_D1_IC_PTA3_PPR (IN_Main_EFLASH.IN_D1_IC_PTA3_PPR)
#define _IN_D1_IC_PTA3_TIMEOUT (IN_Main_EFLASH.IN_D1_IC_PTA3_TIMEOUT)
#define _IN_D2_IC_PTB10_PPR (IN_Main_EFLASH.IN_D2_IC_PTB10_PPR)
#define _IN_D2_IC_PTB10_TIMEOUT (IN_Main_EFLASH.IN_D2_IC_PTB10_TIMEOUT)
#define _IN_D3_IC_PTB11_PPR (IN_Main_EFLASH.IN_D3_IC_PTB11_PPR)
#define _IN_D3_IC_PTB11_TIMEOUT (IN_Main_EFLASH.IN_D3_IC_PTB11_TIMEOUT)
#define _IN_D4_IC_PTC10_PPR (IN_Main_EFLASH.IN_D4_IC_PTC10_PPR)
#define _IN_D4_IC_PTC10_TIMEOUT (IN_Main_EFLASH.IN_D4_IC_PTC10_TIMEOUT)
#define _IN_D5_IC_PTC11_PPR (IN_Main_EFLASH.IN_D5_IC_PTC11_PPR)
#define _IN_D5_IC_PTC11_TIMEOUT (IN_Main_EFLASH.IN_D5_IC_PTC11_TIMEOUT)
#define _IN_D6_IC_PTC12_PPR (IN_Main_EFLASH.IN_D6_IC_PTC12_PPR)
#define _IN_D6_IC_PTC12_TIMEOUT (IN_Main_EFLASH.IN_D6_IC_PTC12_TIMEOUT)
#define _IN_D7_IC_PTC13_PPR (IN_Main_EFLASH.IN_D7_IC_PTC13_PPR)
#define _IN_D7_IC_PTC13_TIMEOUT (IN_Main_EFLASH.IN_D7_IC_PTC13_TIMEOUT)
#define _IN_RxTCMChkOkay (IN_Main_IRAM.IN_RxTCMChkOkay)
#define _IN_RxTCMCounter (IN_Main_IRAM.IN_RxTCMCounter)
#define _IN_RxTCMCounterOkay (IN_Main_IRAM.IN_RxTCMCounterOkay)
#define _IN_RxTCMHandle (IN_Main_IRAM.IN_RxTCMHandle)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'IN_MAIN_EVB_IN_dT'
 * ----------------------------------------------------------------------------
 * model name:...................................'IN_dT'
 * memory class:.................................'ICODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */

/* public IN_dT []  */

void IN_MAIN_EVB_IN_dT (void)
{
   /* define local message copies */
   uint16 INInterface_IN_ADC0_PTD4__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC10_PTA1__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC11_PTA0__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC12_PTA7__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC13_PTB13__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC14_PTC1__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC15_PTC2__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC1_PTB12__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC2_PTB0__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC3_PTB1__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC4_PTA6__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC5_PTC0__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC6_PTE2__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC7_PTE6__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC8_PTA15__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_ADC9_PTA16__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D0_IC_PTA2__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D0_PTA2__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D10_PTB5__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D11_PTB4__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D12_PTB3__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D13_PTB2__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D14_PTA9__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D14_PTE11__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D15_PTA8__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D15_PTE10__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D16_PTE12__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D17_PTD17__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D18_PTC9__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D19_PTC8__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D1_IC_PTA3__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D1_PTA3__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D20_PTD8___IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D21_PTD9__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D2_IC_PTB10__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D2_PTB8__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D3_IC_PTB11__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D3_PTB9__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D4_IC_PTC10__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D4_PTB10__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D5_IC_PTC11__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D5_PTB11__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D6_IC_PTC12__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D6_PTC10__IN_MAIN_EVB_IN_dT;
   struct T_INPUTCAPTURE_EVB INInterface_IN_D7_IC_PTC13__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D7_PTC11__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D8_PTD13__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_D9_PTD14__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTA10__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTA11__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTA12__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTA13__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTA14__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTA17__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTA4__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTB14__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTB15__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTB16__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTB17__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTB6__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTB7__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC12__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC13__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC14__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC15__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC16__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC17__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC3__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC4__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC5__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC6__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTC7__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD0__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD0___IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD1__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD10__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD11__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD12__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD15__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD16__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD2__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD3__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD3___IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD5__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD6__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTD7__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE0__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE1__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE13__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE14__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE15__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE16__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE3__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE4__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE5__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE7__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE8__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_GPIOPTE9__IN_MAIN_EVB_IN_dT;
   struct T_LEVERIN_EVB INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT;
   uint16 INInterface_IN_Potentiometer_PTC14__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_SW2_PTC12__IN_MAIN_EVB_IN_dT;
   boolean INInterface_IN_SW3_PTC13__IN_MAIN_EVB_IN_dT;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      INInterface_IN_ADC0_PTD4__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC0_PTD4;
      INInterface_IN_ADC10_PTA1__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC10_PTA1;
      INInterface_IN_ADC11_PTA0__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC11_PTA0;
      INInterface_IN_ADC12_PTA7__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC12_PTA7;
      INInterface_IN_ADC13_PTB13__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC13_PTB13;
      INInterface_IN_ADC14_PTC1__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC14_PTC1;
      INInterface_IN_ADC15_PTC2__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC15_PTC2;
      INInterface_IN_ADC1_PTB12__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC1_PTB12;
      INInterface_IN_ADC2_PTB0__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC2_PTB0;
      INInterface_IN_ADC3_PTB1__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC3_PTB1;
      INInterface_IN_ADC4_PTA6__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC4_PTA6;
      INInterface_IN_ADC5_PTC0__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC5_PTC0;
      INInterface_IN_ADC6_PTE2__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC6_PTE2;
      INInterface_IN_ADC7_PTE6__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC7_PTE6;
      INInterface_IN_ADC8_PTA15__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC8_PTA15;
      INInterface_IN_ADC9_PTA16__IN_MAIN_EVB_IN_dT = INInterface_IN_ADC9_PTA16;
      INInterface_IN_D0_PTA2__IN_MAIN_EVB_IN_dT = INInterface_IN_D0_PTA2;
      INInterface_IN_D10_PTB5__IN_MAIN_EVB_IN_dT = INInterface_IN_D10_PTB5;
      INInterface_IN_D11_PTB4__IN_MAIN_EVB_IN_dT = INInterface_IN_D11_PTB4;
      INInterface_IN_D12_PTB3__IN_MAIN_EVB_IN_dT = INInterface_IN_D12_PTB3;
      INInterface_IN_D13_PTB2__IN_MAIN_EVB_IN_dT = INInterface_IN_D13_PTB2;
      INInterface_IN_D14_PTA9__IN_MAIN_EVB_IN_dT = INInterface_IN_D14_PTA9;
      INInterface_IN_D14_PTE11__IN_MAIN_EVB_IN_dT = INInterface_IN_D14_PTE11;
      INInterface_IN_D15_PTA8__IN_MAIN_EVB_IN_dT = INInterface_IN_D15_PTA8;
      INInterface_IN_D15_PTE10__IN_MAIN_EVB_IN_dT = INInterface_IN_D15_PTE10;
      INInterface_IN_D16_PTE12__IN_MAIN_EVB_IN_dT = INInterface_IN_D16_PTE12;
      INInterface_IN_D17_PTD17__IN_MAIN_EVB_IN_dT = INInterface_IN_D17_PTD17;
      INInterface_IN_D18_PTC9__IN_MAIN_EVB_IN_dT = INInterface_IN_D18_PTC9;
      INInterface_IN_D19_PTC8__IN_MAIN_EVB_IN_dT = INInterface_IN_D19_PTC8;
      INInterface_IN_D1_PTA3__IN_MAIN_EVB_IN_dT = INInterface_IN_D1_PTA3;
      INInterface_IN_D20_PTD8___IN_MAIN_EVB_IN_dT = INInterface_IN_D20_PTD8_;
      INInterface_IN_D21_PTD9__IN_MAIN_EVB_IN_dT = INInterface_IN_D21_PTD9;
      INInterface_IN_D2_PTB8__IN_MAIN_EVB_IN_dT = INInterface_IN_D2_PTB8;
      INInterface_IN_D3_PTB9__IN_MAIN_EVB_IN_dT = INInterface_IN_D3_PTB9;
      INInterface_IN_D4_PTB10__IN_MAIN_EVB_IN_dT = INInterface_IN_D4_PTB10;
      INInterface_IN_D5_PTB11__IN_MAIN_EVB_IN_dT = INInterface_IN_D5_PTB11;
      INInterface_IN_D6_PTC10__IN_MAIN_EVB_IN_dT = INInterface_IN_D6_PTC10;
      INInterface_IN_D7_PTC11__IN_MAIN_EVB_IN_dT = INInterface_IN_D7_PTC11;
      INInterface_IN_D8_PTD13__IN_MAIN_EVB_IN_dT = INInterface_IN_D8_PTD13;
      INInterface_IN_D9_PTD14__IN_MAIN_EVB_IN_dT = INInterface_IN_D9_PTD14;
      INInterface_IN_GPIOPTA10__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTA10;
      INInterface_IN_GPIOPTA11__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTA11;
      INInterface_IN_GPIOPTA12__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTA12;
      INInterface_IN_GPIOPTA13__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTA13;
      INInterface_IN_GPIOPTA14__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTA14;
      INInterface_IN_GPIOPTA17__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTA17;
      INInterface_IN_GPIOPTA4__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTA4;
      INInterface_IN_GPIOPTB14__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTB14;
      INInterface_IN_GPIOPTB15__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTB15;
      INInterface_IN_GPIOPTB16__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTB16;
      INInterface_IN_GPIOPTB17__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTB17;
      INInterface_IN_GPIOPTB6__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTB6;
      INInterface_IN_GPIOPTB7__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTB7;
      INInterface_IN_GPIOPTC12__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC12;
      INInterface_IN_GPIOPTC13__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC13;
      INInterface_IN_GPIOPTC14__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC14;
      INInterface_IN_GPIOPTC15__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC15;
      INInterface_IN_GPIOPTC16__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC16;
      INInterface_IN_GPIOPTC17__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC17;
      INInterface_IN_GPIOPTC3__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC3;
      INInterface_IN_GPIOPTC4__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC4;
      INInterface_IN_GPIOPTC5__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC5;
      INInterface_IN_GPIOPTC6__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC6;
      INInterface_IN_GPIOPTC7__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTC7;
      INInterface_IN_GPIOPTD0__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD0;
      INInterface_IN_GPIOPTD0___IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD0_;
      INInterface_IN_GPIOPTD10__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD10;
      INInterface_IN_GPIOPTD11__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD11;
      INInterface_IN_GPIOPTD12__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD12;
      INInterface_IN_GPIOPTD15__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD15;
      INInterface_IN_GPIOPTD16__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD16;
      INInterface_IN_GPIOPTD1__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD1;
      INInterface_IN_GPIOPTD2__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD2;
      INInterface_IN_GPIOPTD3__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD3;
      INInterface_IN_GPIOPTD3___IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD3_;
      INInterface_IN_GPIOPTD5__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD5;
      INInterface_IN_GPIOPTD6__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD6;
      INInterface_IN_GPIOPTD7__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTD7;
      INInterface_IN_GPIOPTE0__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE0;
      INInterface_IN_GPIOPTE13__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE13;
      INInterface_IN_GPIOPTE14__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE14;
      INInterface_IN_GPIOPTE15__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE15;
      INInterface_IN_GPIOPTE16__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE16;
      INInterface_IN_GPIOPTE1__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE1;
      INInterface_IN_GPIOPTE3__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE3;
      INInterface_IN_GPIOPTE4__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE4;
      INInterface_IN_GPIOPTE5__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE5;
      INInterface_IN_GPIOPTE7__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE7;
      INInterface_IN_GPIOPTE8__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE8;
      INInterface_IN_GPIOPTE9__IN_MAIN_EVB_IN_dT = INInterface_IN_GPIOPTE9;
      INInterface_IN_Potentiometer_PTC14__IN_MAIN_EVB_IN_dT = INInterface_IN_Potentiometer_PTC14;
      INInterface_IN_SW2_PTC12__IN_MAIN_EVB_IN_dT = INInterface_IN_SW2_PTC12;
      INInterface_IN_SW3_PTC13__IN_MAIN_EVB_IN_dT = INInterface_IN_SW3_PTC13;
      memcpy(&(INInterface_IN_D0_IC_PTA2__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D0_IC_PTA2), sizeof(INInterface_IN_D0_IC_PTA2__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_D1_IC_PTA3__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D1_IC_PTA3), sizeof(INInterface_IN_D1_IC_PTA3__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_D2_IC_PTB10__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D2_IC_PTB10), sizeof(INInterface_IN_D2_IC_PTB10__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_D3_IC_PTB11__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D3_IC_PTB11), sizeof(INInterface_IN_D3_IC_PTB11__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_D4_IC_PTC10__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D4_IC_PTC10), sizeof(INInterface_IN_D4_IC_PTC10__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_D5_IC_PTC11__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D5_IC_PTC11), sizeof(INInterface_IN_D5_IC_PTC11__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_D6_IC_PTC12__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D6_IC_PTC12), sizeof(INInterface_IN_D6_IC_PTC12__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_D7_IC_PTC13__IN_MAIN_EVB_IN_dT), &(INInterface_IN_D7_IC_PTC13), sizeof(INInterface_IN_D7_IC_PTC13__IN_MAIN_EVB_IN_dT));
      memcpy(&(INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT), &(INInterface_IN_LeverIn), sizeof(INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT));
      EnableAllInterrupts();
   }
   /* IN_dT: source line #59:  IN_CAN1Config.startCANChannel(0)  */
   IN_CANCONFIG_EVB_startCANChannel(0U);
   /* IN_dT: source line #62:  INInterface.IN_ADC0_PTD4 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortD_4);  */
   /* assignment to INInterface_IN_ADC0_PTD4: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC0_PTD4__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(58U);
   /* IN_dT: source line #63:  INInterface.IN_ADC1_PTB12 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortB_12);  */
   /* assignment to INInterface_IN_ADC1_PTB12: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC1_PTB12__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(30U);
   /* IN_dT: source line #64:  INInterface.IN_ADC2_PTB0 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortB_0);  */
   /* assignment to INInterface_IN_ADC2_PTB0: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC2_PTB0__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(18U);
   /* IN_dT: source line #65:  INInterface.IN_ADC3_PTB1 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortB_1);  */
   /* assignment to INInterface_IN_ADC3_PTB1: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC3_PTB1__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(19U);
   /* IN_dT: source line #66:  INInterface.IN_ADC4_PTA6 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortA_6);  */
   /* assignment to INInterface_IN_ADC4_PTA6: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC4_PTA6__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(6U);
   /* IN_dT: source line #67:  INInterface.IN_ADC5_PTC0 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortC_0);  */
   /* assignment to INInterface_IN_ADC5_PTC0: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC5_PTC0__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(36U);
   /* IN_dT: source line #68:  INInterface.IN_ADC6_PTE2 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortE_2);  */
   /* assignment to INInterface_IN_ADC6_PTE2: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC6_PTE2__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(74U);
   /* IN_dT: source line #69:  INInterface.IN_ADC7_PTE6 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortE_6);  */
   /* assignment to INInterface_IN_ADC7_PTE6: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC7_PTE6__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(78U);
   /* IN_dT: source line #72:  INInterface.IN_ADC8_PTA15 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortA_15);  */
   /* assignment to INInterface_IN_ADC8_PTA15: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC8_PTA15__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(15U);
   /* IN_dT: source line #73:  INInterface.IN_ADC9_PTA16 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortA_16);  */
   /* assignment to INInterface_IN_ADC9_PTA16: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC9_PTA16__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(16U);
   /* IN_dT: source line #74:  INInterface.IN_ADC10_PTA1 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortA_1);  */
   /* assignment to INInterface_IN_ADC10_PTA1: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC10_PTA1__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(1U);
   /* IN_dT: source line #75:  INInterface.IN_ADC11_PTA0 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortA_0);  */
   /* assignment to INInterface_IN_ADC11_PTA0: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC11_PTA0__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(0U);
   /* IN_dT: source line #76:  INInterface.IN_ADC12_PTA7 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortA_7);  */
   /* assignment to INInterface_IN_ADC12_PTA7: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC12_PTA7__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(7U);
   /* IN_dT: source line #77:  INInterface.IN_ADC13_PTB13 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortB_13);  */
   /* assignment to INInterface_IN_ADC13_PTB13: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC13_PTB13__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(31U);
   /* IN_dT: source line #78:  INInterface.IN_ADC14_PTC1 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortC_1);  */
   /* assignment to INInterface_IN_ADC14_PTC1: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC14_PTC1__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(37U);
   /* IN_dT: source line #79:  INInterface.IN_ADC15_PTC2 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortC_2);  */
   /* assignment to INInterface_IN_ADC15_PTC2: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_ADC15_PTC2__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(38U);
   /* IN_dT: source line #82:  INInterface.IN_Potentiometer_PTC14 = IN_GetAnalog.getADCIn(S32K144_Gpio.PortC_14);  */
   /* assignment to INInterface_IN_Potentiometer_PTC14: min=0, max=65535, hex=13107phys+0, limit=(maxBitLength: true, assign: true), zero incl.=true  */
   INInterface_IN_Potentiometer_PTC14__IN_MAIN_EVB_IN_dT = IN_ANAIN_EVB_getADCIn(50U);
   /* IN_dT: source line #86:  INInterface.IN_D0_IC_PTA2 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortA_2, IN_D0_IC_PTA2_TIMEOUT, IN_D0_IC_PTA2_PPR);  */
   memcpy(&INInterface_IN_D0_IC_PTA2__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(2U, _IN_D0_IC_PTA2_TIMEOUT, _IN_D0_IC_PTA2_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #87:  INInterface.IN_D1_IC_PTA3 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortA_3, IN_D1_IC_PTA3_TIMEOUT, IN_D1_IC_PTA3_PPR);  */
   memcpy(&INInterface_IN_D1_IC_PTA3__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(3U, _IN_D1_IC_PTA3_TIMEOUT, _IN_D1_IC_PTA3_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #88:  INInterface.IN_D2_IC_PTB10 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortB_10, IN_D2_IC_PTB10_TIMEOUT, IN_D2_IC_PTB10_PPR);  */
   memcpy(&INInterface_IN_D2_IC_PTB10__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(28U, _IN_D2_IC_PTB10_TIMEOUT, _IN_D2_IC_PTB10_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #89:  INInterface.IN_D3_IC_PTB11 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortB_11, IN_D3_IC_PTB11_TIMEOUT, IN_D3_IC_PTB11_PPR);  */
   memcpy(&INInterface_IN_D3_IC_PTB11__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(29U, _IN_D3_IC_PTB11_TIMEOUT, _IN_D3_IC_PTB11_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #90:  INInterface.IN_D4_IC_PTC10 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortC_10, IN_D4_IC_PTC10_TIMEOUT, IN_D4_IC_PTC10_PPR);  */
   memcpy(&INInterface_IN_D4_IC_PTC10__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(46U, _IN_D4_IC_PTC10_TIMEOUT, _IN_D4_IC_PTC10_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #91:  INInterface.IN_D5_IC_PTC11 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortC_11, IN_D5_IC_PTC11_TIMEOUT, IN_D5_IC_PTC11_PPR);  */
   memcpy(&INInterface_IN_D5_IC_PTC11__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(47U, _IN_D5_IC_PTC11_TIMEOUT, _IN_D5_IC_PTC11_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #92:  INInterface.IN_D6_IC_PTC12 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortC_12, IN_D6_IC_PTC12_TIMEOUT, IN_D6_IC_PTC12_PPR);  */
   memcpy(&INInterface_IN_D6_IC_PTC12__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(48U, _IN_D6_IC_PTC12_TIMEOUT, _IN_D6_IC_PTC12_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #93:  INInterface.IN_D7_IC_PTC13 = IN_InputCapture.getSpeedIn(S32K144_Gpio.PortC_13, IN_D7_IC_PTC13_TIMEOUT, IN_D7_IC_PTC13_PPR);  */
   memcpy(&INInterface_IN_D7_IC_PTC13__IN_MAIN_EVB_IN_dT , IN_INPUTCAPTUREIN_EVB_getSpeedIn(49U, _IN_D7_IC_PTC13_TIMEOUT, _IN_D7_IC_PTC13_PPR) , sizeof(struct T_INPUTCAPTURE_EVB));
   /* IN_dT: source line #97:  INInterface.IN_GPIOPTB6 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_6);  */
   INInterface_IN_GPIOPTB6__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(24U);
   /* IN_dT: source line #98:  INInterface.IN_GPIOPTB7 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_7);  */
   INInterface_IN_GPIOPTB7__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(25U);
   /* IN_dT: source line #99:  INInterface.IN_GPIOPTE0 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_0);  */
   INInterface_IN_GPIOPTE0__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(72U);
   /* IN_dT: source line #100:  INInterface.IN_GPIOPTE9 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_9);  */
   INInterface_IN_GPIOPTE9__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(81U);
   /* IN_dT: source line #101:  INInterface.IN_GPIOPTC5 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_5);  */
   INInterface_IN_GPIOPTC5__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(41U);
   /* IN_dT: source line #102:  INInterface.IN_GPIOPTC4 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_4);  */
   INInterface_IN_GPIOPTC4__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(40U);
   /* IN_dT: source line #103:  INInterface.IN_GPIOPTA10 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_10);  */
   INInterface_IN_GPIOPTA10__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(10U);
   /* IN_dT: source line #104:  INInterface.IN_GPIOPTA4 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_4);  */
   INInterface_IN_GPIOPTA4__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(4U);
   /* IN_dT: source line #107:  INInterface.IN_GPIOPTC7 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_7);  */
   INInterface_IN_GPIOPTC7__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(43U);
   /* IN_dT: source line #108:  INInterface.IN_GPIOPTC6 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_6);  */
   INInterface_IN_GPIOPTC6__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(42U);
   /* IN_dT: source line #109:  INInterface.IN_GPIOPTB17 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_17);  */
   INInterface_IN_GPIOPTB17__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(35U);
   /* IN_dT: source line #110:  INInterface.IN_GPIOPTB14 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_14);  */
   INInterface_IN_GPIOPTB14__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(32U);
   /* IN_dT: source line #111:  INInterface.IN_GPIOPTB15 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_15);  */
   INInterface_IN_GPIOPTB15__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(33U);
   /* IN_dT: source line #112:  INInterface.IN_GPIOPTB16 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_16);  */
   INInterface_IN_GPIOPTB16__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(34U);
   /* IN_dT: source line #113:  INInterface.IN_GPIOPTC14 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_14);  */
   INInterface_IN_GPIOPTC14__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(50U);
   /* IN_dT: source line #114:  INInterface.IN_GPIOPTC3 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_3);  */
   INInterface_IN_GPIOPTC3__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(39U);
   /* IN_dT: source line #117:  INInterface.IN_GPIOPTE16 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_16);  */
   INInterface_IN_GPIOPTE16__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(88U);
   /* IN_dT: source line #118:  INInterface.IN_GPIOPTE15 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_15);  */
   INInterface_IN_GPIOPTE15__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(87U);
   /* IN_dT: source line #119:  INInterface.IN_GPIOPTE14 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_14);  */
   INInterface_IN_GPIOPTE14__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(86U);
   /* IN_dT: source line #120:  INInterface.IN_GPIOPTE13 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_13);  */
   INInterface_IN_GPIOPTE13__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(85U);
   /* IN_dT: source line #121:  INInterface.IN_GPIOPTE1 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_1);  */
   INInterface_IN_GPIOPTE1__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(73U);
   /* IN_dT: source line #122:  INInterface.IN_GPIOPTD7 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_7);  */
   INInterface_IN_GPIOPTD7__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(61U);
   /* IN_dT: source line #123:  INInterface.IN_GPIOPTD6 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_6);  */
   INInterface_IN_GPIOPTD6__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(60U);
   /* IN_dT: source line #124:  INInterface.IN_GPIOPTC15 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_15);  */
   INInterface_IN_GPIOPTC15__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(51U);
   /* IN_dT: source line #127:  INInterface.IN_D15_PTE10 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_10);  */
   INInterface_IN_D15_PTE10__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(82U);
   /* IN_dT: source line #128:  INInterface.IN_D14_PTE11 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_11);  */
   INInterface_IN_D14_PTE11__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(83U);
   /* IN_dT: source line #129:  INInterface.IN_D13_PTB2 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_2);  */
   INInterface_IN_D13_PTB2__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(20U);
   /* IN_dT: source line #130:  INInterface.IN_D12_PTB3 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_3);  */
   INInterface_IN_D12_PTB3__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(21U);
   /* IN_dT: source line #131:  INInterface.IN_D11_PTB4 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_4);  */
   INInterface_IN_D11_PTB4__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(22U);
   /* IN_dT: source line #132:  INInterface.IN_D10_PTB5 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_5);  */
   INInterface_IN_D10_PTB5__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(23U);
   /* IN_dT: source line #133:  INInterface.IN_D9_PTD14 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_14);  */
   INInterface_IN_D9_PTD14__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(68U);
   /* IN_dT: source line #134:  INInterface.IN_D8_PTD13 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_13);  */
   INInterface_IN_D8_PTD13__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(67U);
   /* IN_dT: source line #137:  INInterface.IN_D7_PTC11 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_11);  */
   INInterface_IN_D7_PTC11__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(47U);
   /* IN_dT: source line #138:  INInterface.IN_D6_PTC10 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_10);  */
   INInterface_IN_D6_PTC10__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(46U);
   /* IN_dT: source line #139:  INInterface.IN_D5_PTB11 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_11);  */
   INInterface_IN_D5_PTB11__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(29U);
   /* IN_dT: source line #140:  INInterface.IN_D4_PTB10 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_10);  */
   INInterface_IN_D4_PTB10__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(28U);
   /* IN_dT: source line #141:  INInterface.IN_D3_PTB9 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_9);  */
   INInterface_IN_D3_PTB9__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(27U);
   /* IN_dT: source line #142:  INInterface.IN_D2_PTB8 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortB_8);  */
   INInterface_IN_D2_PTB8__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(26U);
   /* IN_dT: source line #143:  INInterface.IN_D1_PTA3 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_3);  */
   INInterface_IN_D1_PTA3__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(3U);
   /* IN_dT: source line #144:  INInterface.IN_D0_PTA2 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_2);  */
   INInterface_IN_D0_PTA2__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(2U);
   /* IN_dT: source line #147:  INInterface.IN_D14_PTA9 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_9);  */
   INInterface_IN_D14_PTA9__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(9U);
   /* IN_dT: source line #148:  INInterface.IN_D15_PTA8 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_8);  */
   INInterface_IN_D15_PTA8__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(8U);
   /* IN_dT: source line #149:  INInterface.IN_D16_PTE12 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_12);  */
   INInterface_IN_D16_PTE12__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(84U);
   /* IN_dT: source line #150:  INInterface.IN_D17_PTD17 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_17);  */
   INInterface_IN_D17_PTD17__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(71U);
   /* IN_dT: source line #151:  INInterface.IN_D18_PTC9 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_9);  */
   INInterface_IN_D18_PTC9__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(45U);
   /* IN_dT: source line #152:  INInterface.IN_D19_PTC8 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_8);  */
   INInterface_IN_D19_PTC8__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(44U);
   /* IN_dT: source line #153:  INInterface.IN_D20_PTD8_ = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_8);  */
   INInterface_IN_D20_PTD8___IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(62U);
   /* IN_dT: source line #154:  INInterface.IN_D21_PTD9 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_9);  */
   INInterface_IN_D21_PTD9__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(63U);
   /* IN_dT: source line #155:  INInterface.IN_GPIOPTD2 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_2);  */
   INInterface_IN_GPIOPTD2__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(56U);
   /* IN_dT: source line #156:  INInterface.IN_GPIOPTD0_ = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_0);  */
   INInterface_IN_GPIOPTD0___IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(54U);
   /* IN_dT: source line #159:  INInterface.IN_GPIOPTA14 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_14);  */
   INInterface_IN_GPIOPTA14__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(14U);
   /* IN_dT: source line #160:  INInterface.IN_GPIOPTE7 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_7);  */
   INInterface_IN_GPIOPTE7__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(79U);
   /* IN_dT: source line #161:  INInterface.IN_GPIOPTC13 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_13);  */
   INInterface_IN_GPIOPTC13__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(49U);
   /* IN_dT: source line #162:  INInterface.IN_GPIOPTC12 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_12);  */
   INInterface_IN_GPIOPTC12__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(48U);
   /* IN_dT: source line #163:  INInterface.IN_GPIOPTE8 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_8);  */
   INInterface_IN_GPIOPTE8__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(80U);
   /* IN_dT: source line #164:  INInterface.IN_GPIOPTD0 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_0);  */
   INInterface_IN_GPIOPTD0__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(54U);
   /* IN_dT: source line #165:  INInterface.IN_GPIOPTD16 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_16);  */
   INInterface_IN_GPIOPTD16__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(70U);
   /* IN_dT: source line #166:  INInterface.IN_GPIOPTD15 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_15);  */
   INInterface_IN_GPIOPTD15__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(69U);
   /* IN_dT: source line #169:  INInterface.IN_GPIOPTE3 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_3);  */
   INInterface_IN_GPIOPTE3__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(75U);
   /* IN_dT: source line #170:  INInterface.IN_GPIOPTD3 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_3);  */
   INInterface_IN_GPIOPTD3__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(57U);
   /* IN_dT: source line #171:  INInterface.IN_GPIOPTD5 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_5);  */
   INInterface_IN_GPIOPTD5__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(59U);
   /* IN_dT: source line #172:  INInterface.IN_GPIOPTD12 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_12);  */
   INInterface_IN_GPIOPTD12__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(66U);
   /* IN_dT: source line #173:  INInterface.IN_GPIOPTD11 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_11);  */
   INInterface_IN_GPIOPTD11__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(65U);
   /* IN_dT: source line #174:  INInterface.IN_GPIOPTD10 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_10);  */
   INInterface_IN_GPIOPTD10__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(64U);
   /* IN_dT: source line #175:  INInterface.IN_GPIOPTA17 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_17);  */
   INInterface_IN_GPIOPTA17__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(17U);
   /* IN_dT: source line #176:  INInterface.IN_GPIOPTA11 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_11);  */
   INInterface_IN_GPIOPTA11__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(11U);
   /* IN_dT: source line #179:  INInterface.IN_GPIOPTE4 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_4);  */
   INInterface_IN_GPIOPTE4__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(76U);
   /* IN_dT: source line #180:  INInterface.IN_GPIOPTE5 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortE_5);  */
   INInterface_IN_GPIOPTE5__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(77U);
   /* IN_dT: source line #181:  INInterface.IN_GPIOPTA12 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_12);  */
   INInterface_IN_GPIOPTA12__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(12U);
   /* IN_dT: source line #182:  INInterface.IN_GPIOPTA13 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortA_13);  */
   INInterface_IN_GPIOPTA13__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(13U);
   /* IN_dT: source line #183:  INInterface.IN_GPIOPTC16 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_16);  */
   INInterface_IN_GPIOPTC16__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(52U);
   /* IN_dT: source line #184:  INInterface.IN_GPIOPTC17 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_17);  */
   INInterface_IN_GPIOPTC17__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(53U);
   /* IN_dT: source line #185:  INInterface.IN_GPIOPTD3_ = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_3);  */
   INInterface_IN_GPIOPTD3___IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(57U);
   /* IN_dT: source line #186:  INInterface.IN_GPIOPTD1 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortD_1);  */
   INInterface_IN_GPIOPTD1__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(55U);
   /* IN_dT: source line #189:  INInterface.IN_SW2_PTC12 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_12);  */
   INInterface_IN_SW2_PTC12__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(48U);
   /* IN_dT: source line #190:  INInterface.IN_SW3_PTC13 = IN_DigitalInput.getDigitalIn(S32K144_Gpio.PortC_13);  */
   INInterface_IN_SW3_PTC13__IN_MAIN_EVB_IN_dT = IN_DIGITALIN_EVB_getDigitalIn(49U);
   /* IN_dT: source line #194:  IN_CANRxNewData = IN_CAN_RxTCM.rxCANNewData(IN_RxTCMHandle);  */
   _IN_CANRxNewData = IN_CANRXTCM_EVB_rxCANNewData(_IN_RxTCMHandle);
   /* IN_dT: source line #195:  if (IN_CANRxNewData)  */
   if (_IN_CANRxNewData)
   {
      /* IN_dT: source line #196:  IN_CANTCMData = IN_CAN_RxTCM.rxCANMsg();  */
      memcpy(_IN_CANTCMData_REF_ , IN_CANRXTCM_EVB_rxCANMsg() , sizeof(struct T_CANTCMLEVER_EVB));
      /* IN_dT: source line #197:  IN_RxTCMChkOkay = IN_CANTCMData.TCM_ChecksumOkay;  */
      _IN_RxTCMChkOkay = _IN_CANTCMData.TCM_ChecksumOkay;
      /* IN_dT: source line #198:  IN_RxTCMCounter = IN_CANTCMData.TCM_Counter;  */
      /* assignment to IN_RxTCMCounter: min=0, max=15, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      _IN_RxTCMCounter = _IN_CANTCMData.TCM_Counter;
      /* IN_dT: source line #199:  IN_RxTCMCounterOkay = IN_CANTxTCMCountTest.LIB_CheckOkay(IN_RxTCMCounter);  */
      _IN_RxTCMCounterOkay
         = LIB_4BITCOUNTTEST_EVB_LIB_CheckOkay(_IN_CANTxTCMCountTest_REF_, _IN_RxTCMCounter);
   } /* end if */
   /* IN_dT: source line #201:  IN_CANRxTCMStatus = IN_CANRxTCMStatCheck.LIB_Status(IN_CANRxNewData, IN_RxTCMCounterOkay, IN_CANRXTCMTIMEOUT, SY_1ms);  */
   _IN_CANRxTCMStatus
      = LIB_CANSTATUS_EVB_LIB_Status(_IN_CANRxTCMStatCheck_REF_, _IN_CANRxNewData, _IN_RxTCMCounterOkay, _IN_CANRXTCMTIMEOUT, SY_1MS);
   /* IN_dT: source line #202:  if (IN_RxTCMCounterOkay && IN_CANRxNewData)  */
   if ((_IN_RxTCMCounterOkay) && (_IN_CANRxNewData))
   {
      /* IN_dT: source line #203:  INInterface.IN_LeverIn.TCM_ParkLight = IN_CANTCMData.TCM_ParkLight;  */
      /* assignment to INInterface_IN_LeverIn.TCM_ParkLight: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_ParkLight = _IN_CANTCMData.TCM_ParkLight;
      /* IN_dT: source line #204:  INInterface.IN_LeverIn.TCM_ReverseLight = IN_CANTCMData.TCM_ReverseLight;  */
      /* assignment to INInterface_IN_LeverIn.TCM_ReverseLight: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_ReverseLight = _IN_CANTCMData.TCM_ReverseLight;
      /* IN_dT: source line #205:  INInterface.IN_LeverIn.TCM_NeutralLight = IN_CANTCMData.TCM_NeutralLight;  */
      /* assignment to INInterface_IN_LeverIn.TCM_NeutralLight: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_NeutralLight = _IN_CANTCMData.TCM_NeutralLight;
      /* IN_dT: source line #206:  INInterface.IN_LeverIn.TCM_DriveLight = IN_CANTCMData.TCM_DriveLight;  */
      /* assignment to INInterface_IN_LeverIn.TCM_DriveLight: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_DriveLight = _IN_CANTCMData.TCM_DriveLight;
      /* IN_dT: source line #207:  INInterface.IN_LeverIn.TCM_ManualLight = IN_CANTCMData.TCM_ManualLight;  */
      /* assignment to INInterface_IN_LeverIn.TCM_ManualLight: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_ManualLight = _IN_CANTCMData.TCM_ManualLight;
      /* IN_dT: source line #208:  INInterface.IN_LeverIn.TCM_SportLight = IN_CANTCMData.TCM_SportLight;  */
      /* assignment to INInterface_IN_LeverIn.TCM_SportLight: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_SportLight = _IN_CANTCMData.TCM_SportLight;
      /* IN_dT: source line #209:  INInterface.IN_LeverIn.TCM_ShiftLock = IN_CANTCMData.TCM_ShiftLock;  */
      /* assignment to INInterface_IN_LeverIn.TCM_ShiftLock: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_ShiftLock = _IN_CANTCMData.TCM_ShiftLock;
      /* IN_dT: source line #210:  INInterface.IN_LeverIn.TCM_BackLight = IN_CANTCMData.TCM_BackLight;  */
      /* assignment to INInterface_IN_LeverIn.TCM_BackLight: min=0, max=3, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_BackLight = _IN_CANTCMData.TCM_BackLight;
      /* IN_dT: source line #211:  INInterface.IN_LeverIn.TCM_ActualGear = IN_CANTCMData.TCM_ActualGear;  */
      /* assignment to INInterface_IN_LeverIn.TCM_ActualGear: min=0, max=15, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_ActualGear = _IN_CANTCMData.TCM_ActualGear;
      /* IN_dT: source line #212:  INInterface.IN_LeverIn.TCM_TargetGear = IN_CANTCMData.TCM_TargetGear;  */
      /* assignment to INInterface_IN_LeverIn.TCM_TargetGear: min=0, max=15, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_TargetGear = _IN_CANTCMData.TCM_TargetGear;
      /* IN_dT: source line #213:  INInterface.IN_LeverIn.TCM_TestData1 = IN_CANTCMData.TCM_TestData1;  */
      /* assignment to INInterface_IN_LeverIn.TCM_TestData1: min=0, max=255, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_TestData1 = _IN_CANTCMData.TCM_TestData1;
      /* IN_dT: source line #214:  INInterface.IN_LeverIn.TCM_TestData2 = IN_CANTCMData.TCM_TestData2;  */
      /* assignment to INInterface_IN_LeverIn.TCM_TestData2: min=0, max=255, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
      INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_TestData2 = _IN_CANTCMData.TCM_TestData2;
   } /* end if */
   /* IN_dT: source line #216:  INInterface.IN_LeverIn.TCM_Status = IN_CANRxTCMStatus;  */
   INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT.TCM_Status = _IN_CANRxTCMStatus;
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      INInterface_IN_ADC0_PTD4 = INInterface_IN_ADC0_PTD4__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC10_PTA1 = INInterface_IN_ADC10_PTA1__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC11_PTA0 = INInterface_IN_ADC11_PTA0__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC12_PTA7 = INInterface_IN_ADC12_PTA7__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC13_PTB13 = INInterface_IN_ADC13_PTB13__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC14_PTC1 = INInterface_IN_ADC14_PTC1__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC15_PTC2 = INInterface_IN_ADC15_PTC2__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC1_PTB12 = INInterface_IN_ADC1_PTB12__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC2_PTB0 = INInterface_IN_ADC2_PTB0__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC3_PTB1 = INInterface_IN_ADC3_PTB1__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC4_PTA6 = INInterface_IN_ADC4_PTA6__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC5_PTC0 = INInterface_IN_ADC5_PTC0__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC6_PTE2 = INInterface_IN_ADC6_PTE2__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC7_PTE6 = INInterface_IN_ADC7_PTE6__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC8_PTA15 = INInterface_IN_ADC8_PTA15__IN_MAIN_EVB_IN_dT;
      INInterface_IN_ADC9_PTA16 = INInterface_IN_ADC9_PTA16__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D0_PTA2 = INInterface_IN_D0_PTA2__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D10_PTB5 = INInterface_IN_D10_PTB5__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D11_PTB4 = INInterface_IN_D11_PTB4__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D12_PTB3 = INInterface_IN_D12_PTB3__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D13_PTB2 = INInterface_IN_D13_PTB2__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D14_PTA9 = INInterface_IN_D14_PTA9__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D14_PTE11 = INInterface_IN_D14_PTE11__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D15_PTA8 = INInterface_IN_D15_PTA8__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D15_PTE10 = INInterface_IN_D15_PTE10__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D16_PTE12 = INInterface_IN_D16_PTE12__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D17_PTD17 = INInterface_IN_D17_PTD17__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D18_PTC9 = INInterface_IN_D18_PTC9__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D19_PTC8 = INInterface_IN_D19_PTC8__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D1_PTA3 = INInterface_IN_D1_PTA3__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D20_PTD8_ = INInterface_IN_D20_PTD8___IN_MAIN_EVB_IN_dT;
      INInterface_IN_D21_PTD9 = INInterface_IN_D21_PTD9__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D2_PTB8 = INInterface_IN_D2_PTB8__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D3_PTB9 = INInterface_IN_D3_PTB9__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D4_PTB10 = INInterface_IN_D4_PTB10__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D5_PTB11 = INInterface_IN_D5_PTB11__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D6_PTC10 = INInterface_IN_D6_PTC10__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D7_PTC11 = INInterface_IN_D7_PTC11__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D8_PTD13 = INInterface_IN_D8_PTD13__IN_MAIN_EVB_IN_dT;
      INInterface_IN_D9_PTD14 = INInterface_IN_D9_PTD14__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTA10 = INInterface_IN_GPIOPTA10__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTA11 = INInterface_IN_GPIOPTA11__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTA12 = INInterface_IN_GPIOPTA12__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTA13 = INInterface_IN_GPIOPTA13__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTA14 = INInterface_IN_GPIOPTA14__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTA17 = INInterface_IN_GPIOPTA17__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTA4 = INInterface_IN_GPIOPTA4__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTB14 = INInterface_IN_GPIOPTB14__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTB15 = INInterface_IN_GPIOPTB15__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTB16 = INInterface_IN_GPIOPTB16__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTB17 = INInterface_IN_GPIOPTB17__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTB6 = INInterface_IN_GPIOPTB6__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTB7 = INInterface_IN_GPIOPTB7__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC12 = INInterface_IN_GPIOPTC12__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC13 = INInterface_IN_GPIOPTC13__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC14 = INInterface_IN_GPIOPTC14__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC15 = INInterface_IN_GPIOPTC15__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC16 = INInterface_IN_GPIOPTC16__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC17 = INInterface_IN_GPIOPTC17__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC3 = INInterface_IN_GPIOPTC3__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC4 = INInterface_IN_GPIOPTC4__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC5 = INInterface_IN_GPIOPTC5__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC6 = INInterface_IN_GPIOPTC6__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTC7 = INInterface_IN_GPIOPTC7__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD0 = INInterface_IN_GPIOPTD0__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD0_ = INInterface_IN_GPIOPTD0___IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD1 = INInterface_IN_GPIOPTD1__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD10 = INInterface_IN_GPIOPTD10__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD11 = INInterface_IN_GPIOPTD11__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD12 = INInterface_IN_GPIOPTD12__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD15 = INInterface_IN_GPIOPTD15__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD16 = INInterface_IN_GPIOPTD16__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD2 = INInterface_IN_GPIOPTD2__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD3 = INInterface_IN_GPIOPTD3__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD3_ = INInterface_IN_GPIOPTD3___IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD5 = INInterface_IN_GPIOPTD5__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD6 = INInterface_IN_GPIOPTD6__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTD7 = INInterface_IN_GPIOPTD7__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE0 = INInterface_IN_GPIOPTE0__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE1 = INInterface_IN_GPIOPTE1__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE13 = INInterface_IN_GPIOPTE13__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE14 = INInterface_IN_GPIOPTE14__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE15 = INInterface_IN_GPIOPTE15__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE16 = INInterface_IN_GPIOPTE16__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE3 = INInterface_IN_GPIOPTE3__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE4 = INInterface_IN_GPIOPTE4__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE5 = INInterface_IN_GPIOPTE5__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE7 = INInterface_IN_GPIOPTE7__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE8 = INInterface_IN_GPIOPTE8__IN_MAIN_EVB_IN_dT;
      INInterface_IN_GPIOPTE9 = INInterface_IN_GPIOPTE9__IN_MAIN_EVB_IN_dT;
      INInterface_IN_Potentiometer_PTC14 = INInterface_IN_Potentiometer_PTC14__IN_MAIN_EVB_IN_dT;
      INInterface_IN_SW2_PTC12 = INInterface_IN_SW2_PTC12__IN_MAIN_EVB_IN_dT;
      INInterface_IN_SW3_PTC13 = INInterface_IN_SW3_PTC13__IN_MAIN_EVB_IN_dT;
      memcpy(&(INInterface_IN_D0_IC_PTA2), &(INInterface_IN_D0_IC_PTA2__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D0_IC_PTA2));
      memcpy(&(INInterface_IN_D1_IC_PTA3), &(INInterface_IN_D1_IC_PTA3__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D1_IC_PTA3));
      memcpy(&(INInterface_IN_D2_IC_PTB10), &(INInterface_IN_D2_IC_PTB10__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D2_IC_PTB10));
      memcpy(&(INInterface_IN_D3_IC_PTB11), &(INInterface_IN_D3_IC_PTB11__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D3_IC_PTB11));
      memcpy(&(INInterface_IN_D4_IC_PTC10), &(INInterface_IN_D4_IC_PTC10__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D4_IC_PTC10));
      memcpy(&(INInterface_IN_D5_IC_PTC11), &(INInterface_IN_D5_IC_PTC11__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D5_IC_PTC11));
      memcpy(&(INInterface_IN_D6_IC_PTC12), &(INInterface_IN_D6_IC_PTC12__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D6_IC_PTC12));
      memcpy(&(INInterface_IN_D7_IC_PTC13), &(INInterface_IN_D7_IC_PTC13__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_D7_IC_PTC13));
      memcpy(&(INInterface_IN_LeverIn), &(INInterface_IN_LeverIn__IN_MAIN_EVB_IN_dT), sizeof(INInterface_IN_LeverIn));
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'IN_MAIN_EVB_IN_dT'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'IN_MAIN_EVB_IN_Init'
 * ----------------------------------------------------------------------------
 * model name:...................................'IN_Init'
 * memory class:.................................'ICODE'
 * ---------------------------------------------------------------------------*/
/* public IN_Init []  */

void IN_MAIN_EVB_IN_Init (void)
{
   /* IN_Init: source line #223:  IN_CAN1Config.initCANChannel(0, 500)  */
   IN_CANCONFIG_EVB_initCANChannel(0U, 500U);
   /* IN_Init: source line #225:  IN_RxTCMHandle = IN_CANMsgInit.initCANMsg(IN_CANRXTCMCHAN, IN_CANRXTCMID, false, false, IN_CANRXTCMLEN);  */
   /* assignment to IN_RxTCMHandle: min=-128, max=127, hex=1phys+0, limit=(maxBitLength: false, assign: true), zero incl.=true  */
   _IN_RxTCMHandle
      = IN_CANMESSAGEINIT_EVB_initCANMsg(_IN_CANRXTCMCHAN, _IN_CANRXTCMID, false, false, _IN_CANRXTCMLEN);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'IN_MAIN_EVB_IN_Init'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



