/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.OUT.OUT_DigitalOutput
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_OUT_DIGITALOUTPUT_EVB_H_
#define _ASD_OUT_DIGITALOUTPUT_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"


/* component structure for class OUT_DIGITALOUTPUT_EVB intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......................OUT_DIGITALOUTPUT_EVB */
#define _OUT_DIGITALOUTPUT_EVB_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class OUT_DIGITALOUTPUT_EVB
 ******************************************************************************/
extern void OUT_DIGITALOUTPUT_EVB_setDigOut (
   /* IN    */ uint8   port,
   /* IN    */ boolean stat
   );



#endif /* _ASD_OUT_DIGITALOUTPUT_EVB_H_ */
