/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................ascet.OUT.OUT_CANTxIC
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_OUT_CANTXIC_EVB_H_
#define _ASD_OUT_CANTXIC_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"
#include "T_InputCapture_EVB.h"


/* component structure for class OUT_CANTXIC_EVB intentionally not created    */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............................OUT_CANTXIC_EVB */
#define _OUT_CANTXIC_EVB_TYPE_DEF_




/* forward declaration of types used for method arguments */
#ifndef _T_INPUTCAPTURE_EVB_TYPE_DEF_
struct T_INPUTCAPTURE_EVB;
#endif

/******************************************************************************
 * BEGIN: declaration of global C functions defined by class OUT_CANTXIC_EVB
 ******************************************************************************/
extern uint8 OUT_CANTXIC_EVB_txCANMsg (
   /* IN    */ sint8                       OUT_CANTxHandle,
   /* IN    */ struct T_INPUTCAPTURE_EVB * OUT_CANTxMsg,
   /* IN    */ boolean                     OUT_CANTxMux
   );



#endif /* _ASD_OUT_CANTXIC_EVB_H_ */
