/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.5.0
 * CODE GENERATOR:..............V7.5.0
 * COMPONENT:...................types.T_InputCapture
 * REPRESENTATION:..............EVB
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_T_INPUTCAPTURE_EVB_H_
#define _ASD_T_INPUTCAPTURE_EVB_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "sysconsts.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF RECORD STRUCTURE 'T_InputCapture'
 * ---------------------------------------------------------------------------*/
struct T_INPUTCAPTURE_EVB {
   uint32 IN_HighTime;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint32 IN_Period;	/* min=0.0, max=4294967295.0, esdl_f1_0, limit=yes */
   uint16 IN_Duty;	/* min=0.0, max=100.0, esdl_f0_01, limit=yes */
   sint16 IN_Speed;	/* min=-32768.0, max=32767.0, f_0bn0, limit=yes */
   boolean IN_Pin;	/* min=0, max=1, Identity, limit=yes */
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF RECORD STRUCTURE 'T_InputCapture'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........................T_INPUTCAPTURE_EVB */
#define _T_INPUTCAPTURE_EVB_TYPE_DEF_


#endif /* _ASD_T_INPUTCAPTURE_EVB_H_ */
