/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................BalanceBot
 * REPRESENTATION:..............
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_BALANCEBOT_AUTOMATIC_H_
#define _ASD_BALANCEBOT_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "classes_AngleSpeedController_Automatic.h"
#include "classes_TurnSpeedController_Automatic.h"
#include "classes_VehicleSpeedController_Automatic.h"
#include "control_RemoteCommandsMain_Automatic.h"
#include "interfaces_IBalance2WD_Automatic.h"
#include "interfaces_IParameters_Automatic.h"
#include "interfaces_IRemoteCommands_Automatic.h"
#include "SystemLib_Miscellaneous_DeltaTimeService_Automatic.h"


/* component structure for project BALANCEBOT_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .......................BalanceBot_Automatic */
#define _BalanceBot_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project BalanceBot_Automatic
 ******************************************************************************/



#endif /* _ASD_BALANCEBOT_AUTOMATIC_H_ */
