/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................classes.AngleSpeedController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_CLASSES_ANGLESPEEDCONTROLLER_AUTOMATIC_H_
#define _ASD_CLASSES_ANGLESPEEDCONTROLLER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "SystemLib_Math_MathLib_R64.h"
#include "SystemLib_Nonlinears_Limiter_Automatic.h"
#include "SystemLib_Transferfunction_Integrator_IntegratorKLimited_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'classes_AngleSpeedController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct classes_AngleSpeedController_Automatic_RAM_SUBSTRUCT {
   float32 currentAngle;
   float32 errorAngleSum;
   float32 prevAngle;
   struct SystemLib_Transferfunction_Integrator_IntegratorKLimited_Automatic_RAM_SUBSTRUCT IntegratorKLimited_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'classes_AngleSpeedController_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'classes_AngleSpeedController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct classes_AngleSpeedController_Automatic {
   struct SystemLib_Transferfunction_Integrator_IntegratorKLimited_Automatic IntegratorKLimited_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'classes_AngleSpeedController_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .....classes_AngleSpeedController_Automatic */
#define _classes_AngleSpeedController_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'classes_AngleSpeedController_RAM' */
/* containing 'RAM' memory class tree */
extern struct classes_AngleSpeedController_Automatic_RAM_SUBSTRUCT classes_AngleSpeedController_RAM;

/* forward declaration of component variable 'classes_AngleSpeedController' */
/* containing 'ROM' memory class tree */
extern const struct classes_AngleSpeedController_Automatic classes_AngleSpeedController;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module classes_AngleSpeedController_Automatic
 ******************************************************************************/
extern void classes_AngleSpeedController_Automatic_calculateAngleSpeed (void);
extern void classes_AngleSpeedController_Automatic_calculateInclinationAngle (void);



#endif /* _ASD_CLASSES_ANGLESPEEDCONTROLLER_AUTOMATIC_H_ */
