/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................classes.VehicleSpeedController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_CLASSES_VEHICLESPEEDCONTROLLER_AUTOMATIC_H_
#define _ASD_CLASSES_VEHICLESPEEDCONTROLLER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "SystemLib_Transferfunction_Integrator_IntegratorKLimited_Automatic.h"
#include "SystemLib_Transferfunction_Lowpass_DigitalLowpass_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'classes_VehicleSpeedController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct classes_VehicleSpeedController_Automatic_RAM_SUBSTRUCT {
   float32 errorSpeedSum;
   struct SystemLib_Transferfunction_Lowpass_DigitalLowpass_Automatic_RAM_SUBSTRUCT DigitalLowpass_Speed;
   struct SystemLib_Transferfunction_Lowpass_DigitalLowpass_Automatic_RAM_SUBSTRUCT DigitalLowpass_TargetSpeed;
   struct SystemLib_Transferfunction_Integrator_IntegratorKLimited_Automatic_RAM_SUBSTRUCT Integrator_Speed;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'classes_VehicleSpeedController_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'classes_VehicleSpeedController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct classes_VehicleSpeedController_Automatic {
   struct SystemLib_Transferfunction_Lowpass_DigitalLowpass_Automatic DigitalLowpass_Speed;
   struct SystemLib_Transferfunction_Lowpass_DigitalLowpass_Automatic DigitalLowpass_TargetSpeed;
   struct SystemLib_Transferfunction_Integrator_IntegratorKLimited_Automatic Integrator_Speed;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'classes_VehicleSpeedController_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...classes_VehicleSpeedController_Automatic */
#define _classes_VehicleSpeedController_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'classes_VehicleSpeedController_RAM' */
/* containing 'RAM' memory class tree */
extern struct classes_VehicleSpeedController_Automatic_RAM_SUBSTRUCT classes_VehicleSpeedController_RAM;

/* forward declaration of component variable 'classes_VehicleSpeedController' */
/* containing 'ROM' memory class tree */
extern const struct classes_VehicleSpeedController_Automatic classes_VehicleSpeedController;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module classes_VehicleSpeedController_Automatic
 ******************************************************************************/
extern void classes_VehicleSpeedController_Automatic_init (void);
extern void classes_VehicleSpeedController_Automatic_calculateVehicleSpeed (void);



#endif /* _ASD_CLASSES_VEHICLESPEEDCONTROLLER_AUTOMATIC_H_ */
