/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................classes.TurnSpeedController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "classes_TurnSpeedController_Automatic.h"
#include "interfaces_IBalance2WD_Automatic.h"
#include "interfaces_IParameters_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'classes_TurnSpeedController_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'classes_TurnSpeedController'
 * data set:.....................................'CLASSES_TURNSPEEDCONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct classes_TurnSpeedController_Automatic_RAM_SUBSTRUCT classes_TurnSpeedController_RAM = {
   /* struct element:'classes_TurnSpeedController_RAM.currentSpeed' (modeled as:'currentSpeed.classes_TurnSpeedController') */
   0.0F,
   /* struct element:'classes_TurnSpeedController_RAM.rotationRatio' (modeled as:'rotationRatio.classes_TurnSpeedController') */
   0.0F,
   /* struct element:'classes_TurnSpeedController_RAM.spinOnce' (modeled as:'spinOnce.classes_TurnSpeedController') */
   0,
   /* struct element:'classes_TurnSpeedController_RAM.turnOut' (modeled as:'turnOut.classes_TurnSpeedController') */
   0.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'classes_TurnSpeedController_RAM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'classes_TurnSpeedController'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/





#define currentSpeed_VAL (classes_TurnSpeedController_RAM.currentSpeed)
#define rotationRatio_VAL (classes_TurnSpeedController_RAM.rotationRatio)
#define spinOnce_VAL (classes_TurnSpeedController_RAM.spinOnce)
#define turnOut_VAL (classes_TurnSpeedController_RAM.turnOut)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'classes_TurnSpeedController_Automatic_calculateTurnSpeed'
 * ----------------------------------------------------------------------------
 * model name:...................................'calculateTurnSpeed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */
#define KpTurn__classes_TurnSpeedController_Automatic_calculateTurnSpeed (KpTurn)
#define PulseLeft__classes_TurnSpeedController_Automatic_calculateTurnSpeed (PulseLeft)
#define PulseRight__classes_TurnSpeedController_Automatic_calculateTurnSpeed (PulseRight)
#define TurnLeftRightFlag__classes_TurnSpeedController_Automatic_calculateTurnSpeed (TurnLeftRightFlag)
#define TurnOutput__classes_TurnSpeedController_Automatic_calculateTurnSpeed (TurnOutput)


void classes_TurnSpeedController_Automatic_calculateTurnSpeed (void)
{
   /* temp. variables */
   float32 _t1real32;

   if (TurnLeftRightFlag__classes_TurnSpeedController_Automatic_calculateTurnSpeed == 0)
   {
      spinOnce_VAL = 0;
      turnOut_VAL = 0.0F;
   }
   else
   {
      if (spinOnce_VAL == 0)
      {
         spinOnce_VAL = 1;
         _t1real32
            = (float32)PulseLeft__classes_TurnSpeedController_Automatic_calculateTurnSpeed + (float32)PulseRight__classes_TurnSpeedController_Automatic_calculateTurnSpeed;
         currentSpeed_VAL = ((_t1real32 > 0.0F) ? _t1real32 : -_t1real32);
         rotationRatio_VAL
            = SystemLib_Nonlinears_Limiter_Automatic_value(0.5F, ((currentSpeed_VAL == 0.0F) ? 55.0F : (55.0F / currentSpeed_VAL)), 5.0F);
      } /* end if */
      turnOut_VAL
         = SystemLib_Nonlinears_Limiter_Automatic_value(-5.0F, turnOut_VAL + (((TurnLeftRightFlag__classes_TurnSpeedController_Automatic_calculateTurnSpeed == 1) ? -rotationRatio_VAL : rotationRatio_VAL)), 5.0F);
   } /* end if */
   TurnOutput__classes_TurnSpeedController_Automatic_calculateTurnSpeed
      = KpTurn__classes_TurnSpeedController_Automatic_calculateTurnSpeed * turnOut_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'classes_TurnSpeedController_Automatic_calculateTurnSpeed'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



