/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................control.RemoteCommandsMain
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_CONTROL_REMOTECOMMANDSMAIN_AUTOMATIC_H_
#define _ASD_CONTROL_REMOTECOMMANDSMAIN_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "classes_Balance2WD_Automatic.h"
#include "control_RemoteCommands_Automatic.h"


/* component structure for module CONTROL_REMOTECOMMANDSMAIN_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .......control_RemoteCommandsMain_Automatic */
#define _control_RemoteCommandsMain_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module control_RemoteCommandsMain_Automatic
 ******************************************************************************/


/******************************************************************************
 * BEGIN: declaration of global C functions defined by module control_RemoteCommandsMain_Automatic
 ******************************************************************************/
extern void control_RemoteCommandsMain_Automatic_calc (void);



#endif /* _ASD_CONTROL_REMOTECOMMANDSMAIN_AUTOMATIC_H_ */
