/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................SystemLib.Nonlinears.Limiter
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Limiter returns the input x limited by mn and mx.
 ******************************************************************************/
#ifndef _ASD_SYSTEMLIB_NONLINEARS_LIMITER_AUTOMATIC_H_
#define _ASD_SYSTEMLIB_NONLINEARS_LIMITER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 7))
# error NOT COMPLIANT (< compliance level 7) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* component structure for class SYSTEMLIB_NONLINEARS_LIMITER_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .....SystemLib_Nonlinears_Limiter_Automatic */
#define _SystemLib_Nonlinears_Limiter_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class SystemLib_Nonlinears_Limiter_Automatic
 ******************************************************************************/
extern float32 SystemLib_Nonlinears_Limiter_Automatic_value (
   /* IN    */ const float32 mn,
   /* IN    */ const float32 x,
   /* IN    */ const float32 mx
   );



#endif /* _ASD_SYSTEMLIB_NONLINEARS_LIMITER_AUTOMATIC_H_ */
