/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.LedController
 * REPRESENTATION:..............stm32f334r8
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_LedController_stm32f334r8.h"
#include "model_RgbLed_stm32f334r8.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define fadeValue_VAL (self->model_LedController_stm32f334r8_RAM->fadeValue)
#define gameState_VAL (self->model_LedController_stm32f334r8_RAM->gameState)
#define gameTime_VAL (self->model_LedController_stm32f334r8_RAM->gameTime)
#define ledRing_VAL (self->model_LedController_stm32f334r8_RAM->ledRing)
#define sm_VAL (self->model_LedController_stm32f334r8_RAM->sm)
#define sw_REF (&(self->sw))

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/


/* definition of label "IdleFading" from enumeration "model_LedController_enum" */
#define IdleFading 0U
/* definition of label "IndicateGameTime" from enumeration "model_LedController_enum" */
#define IndicateGameTime 1U


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_fadeViolet'
 * ----------------------------------------------------------------------------
 * model name:...................................'fadeViolet'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_LedController_stm32f334r8_fadeViolet ( const struct model_LedController_stm32f334r8 * self)
{
   /* user defined local variables */
   uint8 i;
   /* temp. variables */
   float32 _t1real32;

   SystemLib_CounterTimer_StopWatch_Automatic_compute(sw_REF);
   if (SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF) <= 2.0F)
   {
      fadeValue_VAL
         = (SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF) + 0.2F) / 2.2F;
   }
   else
   {
      if (SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF) <= 4.0F)
      {
         fadeValue_VAL
            = (4.2F - SystemLib_CounterTimer_StopWatch_Automatic_value(sw_REF)) / 2.2F;
      }
      else
      {
         SystemLib_CounterTimer_StopWatch_Automatic_reset(sw_REF);
      } /* end if */
   } /* end if */
   for (i = 0U;i <= 11U;++i)
   {
      _t1real32 = fadeValue_VAL * 255.0F;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      _t1real32
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? _t1real32 : 255.0F)) : 0.0F);
      ledRing_VAL[i].red = (uint8)_t1real32;
      ledRing_VAL[i].green = 0U;
      ledRing_VAL[i].blue = (uint8)_t1real32;
   } /* end for */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_fadeViolet'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_indicateGameTime'
 * ----------------------------------------------------------------------------
 * model name:...................................'indicateGameTime'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_LedController_stm32f334r8_indicateGameTime ( const struct model_LedController_stm32f334r8 * self)
{
   /* user defined local variables */
   float32 brightness;
   struct model_RgbLed_stm32f334r8 color;
   uint8 i;
   float32 mappedTime;
   /* temp. variables */
   float32 _t1real32;

   color.red = 0U;
   color.green = 0U;
   color.blue = 255U;
   if (gameTime_VAL <= 0.2F)
   {
      color.red = 255U;
      color.green = 0U;
      color.blue = 0U;
   } /* end if */
   mappedTime = gameTime_VAL * 12.0F;
   for (i = 0U;i <= 11U;++i)
   {
      brightness = mappedTime - (float32)i;
      if (brightness > 1.0F)
      {
         brightness = 1.0F;
      } /* end if */
      if (brightness <= 0.0F)
      {
         brightness = 0.0F;
      } /* end if */
      _t1real32 = (float32)color.red * brightness;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      ledRing_VAL[i].red
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? (uint8)_t1real32 : 255U)) : 0U);
      _t1real32 = (float32)color.green * brightness;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      ledRing_VAL[i].green
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? (uint8)_t1real32 : 255U)) : 0U);
      _t1real32 = (float32)color.blue * brightness;
      _t1real32
         = ((_t1real32 < 0.0F) ? (_t1real32 - 0.5F) : (_t1real32 + 0.5F));
      ledRing_VAL[i].blue
         = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 255.0F) ? (uint8)_t1real32 : 255U)) : 0U);
   } /* end for */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_indicateGameTime'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameIdle'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameIdle'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_LedController_stm32f334r8_isGameIdle ( const struct model_LedController_stm32f334r8 * self)
{
   return gameState_VAL == 0U;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameIdle'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameRunning'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameRunning'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_LedController_stm32f334r8_isGameRunning ( const struct model_LedController_stm32f334r8 * self)
{
   return !model_LedController_stm32f334r8_isGameIdle(self);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_isGameRunning'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_LedController_stm32f334r8_periodicTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'periodicTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_LedController_stm32f334r8_periodicTrigger ( const struct model_LedController_stm32f334r8 * self)
{
   switch (sm_VAL)
   {
      case IndicateGameTime:
         if (model_LedController_stm32f334r8_isGameIdle(self))
         {
            sm_VAL = IdleFading;
            break;
         } /* end if */
         model_LedController_stm32f334r8_indicateGameTime(self);
         break;
      case IdleFading:
      default:
         if (model_LedController_stm32f334r8_isGameRunning(self))
         {
            sm_VAL = IndicateGameTime;
            break;
         } /* end if */
         model_LedController_stm32f334r8_fadeViolet(self);
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_LedController_stm32f334r8_periodicTrigger'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



