/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.ServoController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_ServoController_Automatic.h"
#include "BalanceTube_STMicro_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define ballPosition_VAL (self->model_ServoController_Automatic_RAM->ballPosition)
#define doIntegrate_VAL (self->model_ServoController_Automatic_RAM->doIntegrate)
#define dT_VAL (ASD_DT_SCALED)
#define edgeDetect_REF (&(self->edgeDetect))
#define error_VAL (self->model_ServoController_Automatic_RAM->error)
#define gameState_VAL (self->model_ServoController_Automatic_RAM->gameState)
#define handPosition_VAL (self->model_ServoController_Automatic_RAM->handPosition)
#define integral_VAL (self->model_ServoController_Automatic_RAM->integral)
#define kd_VAL (self->model_ServoController_Automatic_CAL_MEM->kd)
#define ki_VAL (self->model_ServoController_Automatic_CAL_MEM->ki)
#define kp_VAL (self->model_ServoController_Automatic_CAL_MEM->kp)
#define lastValue_VAL (self->model_ServoController_Automatic_RAM->lastValue)
#define servoPosition_VAL (self->model_ServoController_Automatic_RAM->servoPosition)
#define sm_VAL (self->model_ServoController_Automatic_RAM->sm)
#define switchMode_VAL (self->model_ServoController_Automatic_RAM->switchMode)

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/


/* definition of label "AutoMode" from enumeration "model_ServoController_enum" */
#define AutoMode 1U
/* definition of label "IdlePosition" from enumeration "model_ServoController_enum" */
#define IdlePosition 0U
/* definition of label "ManualMode" from enumeration "model_ServoController_enum" */
#define ManualMode 2U


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_autoMode'
 * ----------------------------------------------------------------------------
 * model name:...................................'autoMode'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_ServoController_Automatic_autoMode ( const struct model_ServoController_Automatic * self)
{
   /* temp. variables */
   float32 _t1real32;

   error_VAL = 0.5F - ballPosition_VAL;
   if (doIntegrate_VAL)
   {
      integral_VAL = (ki_VAL * error_VAL * dT_VAL) + integral_VAL;
   } /* end if */
   doIntegrate_VAL = (servoPosition_VAL < 0.9F) && (servoPosition_VAL > 0.1F);
   _t1real32 = (error_VAL - lastValue_VAL) * kd_VAL;
   _t1real32
      = (kp_VAL * error_VAL) + integral_VAL + (((dT_VAL == 0.0F) ? _t1real32 : (_t1real32 / dT_VAL))) + 0.5F;
   servoPosition_VAL
      = ((_t1real32 >= 0.0F) ? (((_t1real32 <= 1.0F) ? _t1real32 : 1.0F)) : 0.0F);
   lastValue_VAL = error_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_autoMode'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameIdle'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameIdle'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_ServoController_Automatic_isGameIdle ( const struct model_ServoController_Automatic * self)
{
   return gameState_VAL == 0U;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameIdle'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameRunning'
 * ----------------------------------------------------------------------------
 * model name:...................................'isGameRunning'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_ServoController_Automatic_isGameRunning ( const struct model_ServoController_Automatic * self)
{
   return !model_ServoController_Automatic_isGameIdle(self);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_isGameRunning'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_periodicTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'periodicTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_ServoController_Automatic_periodicTrigger ( const struct model_ServoController_Automatic * self)
{
   switch (sm_VAL)
   {
      case AutoMode:
         if (model_ServoController_Automatic_isGameIdle(self))
         {
            integral_VAL = 0.0F;
            sm_VAL = IdlePosition;
            break;
         } /* end if */
         if (model_ServoController_Automatic_switchModeButtonPushed(self))
         {
            integral_VAL = 0.0F;
            sm_VAL = ManualMode;
            break;
         } /* end if */
         model_ServoController_Automatic_autoMode(self);
         break;
      case ManualMode:
         if (model_ServoController_Automatic_isGameIdle(self))
         {
            sm_VAL = IdlePosition;
            break;
         } /* end if */
         if (model_ServoController_Automatic_switchModeButtonPushed(self))
         {
            sm_VAL = AutoMode;
            break;
         } /* end if */
         servoPosition_VAL = handPosition_VAL;
         break;
      case IdlePosition:
      default:
         if (model_ServoController_Automatic_isGameRunning(self))
         {
            sm_VAL = ManualMode;
            break;
         } /* end if */
         servoPosition_VAL = 0.5F;
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_periodicTrigger'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_ServoController_Automatic_switchModeButtonPushed'
 * ----------------------------------------------------------------------------
 * model name:...................................'switchModeButtonPushed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_ServoController_Automatic_switchModeButtonPushed ( const struct model_ServoController_Automatic * self)
{
   SystemLib_Miscellaneous_EdgeRising_Impl_compute(edgeDetect_REF, switchMode_VAL);
   return SystemLib_Miscellaneous_EdgeRising_Impl_value(edgeDetect_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_ServoController_Automatic_switchModeButtonPushed'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



