/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.GameController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_GameController_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define ballPosition_VAL (self->model_GameController_Automatic_RAM->ballPosition)
#define edgeDetect_REF (&(self->edgeDetect))
#define gameTime_VAL (self->model_GameController_Automatic_CAL_MEM->gameTime)
#define score_VAL (self->model_GameController_Automatic_RAM->score)
#define scoringZone_VAL (self->model_GameController_Automatic_CAL_MEM->scoringZone)
#define sm_VAL (self->model_GameController_Automatic_RAM->sm)
#define startGame_VAL (self->model_GameController_Automatic_RAM->startGame)
#define stopWatch_REF (&(self->stopWatch))
#define timer_REF (&(self->timer))

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/


/* definition of label "Idle" from enumeration "model_GameController_enum" */
#define Idle 0U
/* definition of label "IncreaseScore" from enumeration "model_GameController_enum" */
#define IncreaseScore 1U
/* definition of label "NotInScoringZone" from enumeration "model_GameController_enum" */
#define NotInScoringZone 2U


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_gameState'
 * ----------------------------------------------------------------------------
 * model name:...................................'gameState'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 model_GameController_Automatic_gameState ( const struct model_GameController_Automatic * self)
{
   return sm_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_gameState'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_getTime'
 * ----------------------------------------------------------------------------
 * model name:...................................'getTime'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 model_GameController_Automatic_getTime ( const struct model_GameController_Automatic * self)
{
   /* temp. variables */
   float32 _t1real32;

   _t1real32 = SystemLib_CounterTimer_Timer_Automatic_getTime(timer_REF);
   return ((gameTime_VAL == 0.0F) ? _t1real32 : (_t1real32 / gameTime_VAL));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_getTime'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_isCanceled'
 * ----------------------------------------------------------------------------
 * model name:...................................'isCanceled'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_GameController_Automatic_isCanceled ( const struct model_GameController_Automatic * self)
{
   if ((gameTime_VAL - SystemLib_CounterTimer_Timer_Automatic_getTime(timer_REF)) <= 2.0F)
   {
      return false;
   } /* end if */
   SystemLib_Miscellaneous_EdgeRising_Impl_compute(edgeDetect_REF, startGame_VAL);
   return SystemLib_Miscellaneous_EdgeRising_Impl_value(edgeDetect_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_isCanceled'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_isInScoringZone'
 * ----------------------------------------------------------------------------
 * model name:...................................'isInScoringZone'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_GameController_Automatic_isInScoringZone ( const struct model_GameController_Automatic * self)
{
   /* temp. variables */
   float32 _t1real32;

   _t1real32 = ballPosition_VAL - 0.5F;
   return (((_t1real32 > 0.0F) ? _t1real32 : -_t1real32)) <= (scoringZone_VAL * 0.5F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_isInScoringZone'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_isStartGameButtonPushed'
 * ----------------------------------------------------------------------------
 * model name:...................................'isStartGameButtonPushed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean model_GameController_Automatic_isStartGameButtonPushed ( const struct model_GameController_Automatic * self)
{
   SystemLib_Miscellaneous_EdgeRising_Impl_compute(edgeDetect_REF, startGame_VAL);
   return SystemLib_Miscellaneous_EdgeRising_Impl_value(edgeDetect_REF);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_isStartGameButtonPushed'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'model_GameController_Automatic_periodicTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'periodicTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void model_GameController_Automatic_periodicTrigger ( const struct model_GameController_Automatic * self)
{
   switch (sm_VAL)
   {
      case IncreaseScore:
         if ((SystemLib_CounterTimer_Timer_Automatic_isElapsed(timer_REF)) || (model_GameController_Automatic_isCanceled(self)))
         {
            sm_VAL = Idle;
            break;
         } /* end if */
         if (!model_GameController_Automatic_isInScoringZone(self))
         {
            SystemLib_CounterTimer_Timer_Automatic_compute(timer_REF);
            sm_VAL = NotInScoringZone;
            break;
         } /* end if */
         SystemLib_CounterTimer_StopWatch_Automatic_compute(stopWatch_REF);
         score_VAL
            = SystemLib_CounterTimer_StopWatch_Automatic_value(stopWatch_REF);
         SystemLib_CounterTimer_Timer_Automatic_compute(timer_REF);
         break;
      case NotInScoringZone:
         if ((SystemLib_CounterTimer_Timer_Automatic_isElapsed(timer_REF)) || (model_GameController_Automatic_isCanceled(self)))
         {
            sm_VAL = Idle;
            break;
         } /* end if */
         if (model_GameController_Automatic_isInScoringZone(self))
         {
            SystemLib_CounterTimer_Timer_Automatic_compute(timer_REF);
            sm_VAL = IncreaseScore;
            break;
         } /* end if */
         SystemLib_CounterTimer_Timer_Automatic_compute(timer_REF);
         break;
      case Idle:
      default:
         if (model_GameController_Automatic_isStartGameButtonPushed(self))
         {
            SystemLib_CounterTimer_Timer_Automatic_begin(timer_REF, gameTime_VAL);
            SystemLib_CounterTimer_StopWatch_Automatic_reset(stopWatch_REF);
            score_VAL = 0.0F;
            sm_VAL = NotInScoringZone;
            break;
         } /* end if */
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'model_GameController_Automatic_periodicTrigger'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



