/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER 7.9.0
 * CODE GENERATOR:..............6.4.7
 * COMPONENT:...................model.MainClass
 * REPRESENTATION:..............stm32f334r8
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "model_MainClass_stm32f334r8.h"
#include "model_RgbLed_stm32f334r8.h"
#include "model_Signals_stm32f334r8.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'model_MainClass_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'model_MainClass'
 * data set:.....................................'MODEL_MAINCLASS_STM32F334R8_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const volatile struct model_MainClass_stm32f334r8_CAL_MEM_SUBSTRUCT model_MainClass_CAL_MEM = {
   /* substruct: model_MainClass_CAL_MEM.gameController (modeled as:'gameController.model_MainClass') */
   {
      /* struct element:'model_MainClass_CAL_MEM.gameController.gameTime' (modeled as:'gameTime.gameController.model_MainClass') */
      120.0F,
      /* struct element:'model_MainClass_CAL_MEM.gameController.scoringZone' (modeled as:'scoringZone.gameController.model_MainClass') */
      0.2F
   },
   /* substruct: model_MainClass_CAL_MEM.servoController (modeled as:'servoController.model_MainClass') */
   {
      /* struct element:'model_MainClass_CAL_MEM.servoController.kd' (modeled as:'kd.servoController.model_MainClass') */
      0.03F,
      /* struct element:'model_MainClass_CAL_MEM.servoController.ki' (modeled as:'ki.servoController.model_MainClass') */
      0.22F,
      /* struct element:'model_MainClass_CAL_MEM.servoController.kp' (modeled as:'kp.servoController.model_MainClass') */
      0.22F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'model_MainClass_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'model_MainClass_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'model_MainClass'
 * data set:.....................................'MODEL_MAINCLASS_STM32F334R8_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct model_MainClass_stm32f334r8_RAM_SUBSTRUCT model_MainClass_RAM = {
   /* substruct: model_MainClass_RAM.gameController (modeled as:'gameController.model_MainClass') */
   {
      /* struct element:'model_MainClass_RAM.gameController.ballPosition' (modeled as:'ballPosition.gameController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.gameController.score' (modeled as:'score.gameController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.gameController.sm' (modeled as:'sm.gameController.model_MainClass') */
      0U /* Idle */,
      /* struct element:'model_MainClass_RAM.gameController.startGame' (modeled as:'startGame.gameController.model_MainClass') */
      false,
      /* substruct: model_MainClass_RAM.gameController.edgeDetect (modeled as:'edgeDetect.gameController.model_MainClass') */
      {
         /* struct element:'model_MainClass_RAM.gameController.edgeDetect.buffer' (modeled as:'buffer.edgeDetect.gameController.model_MainClass') */
         false,
         /* struct element:'model_MainClass_RAM.gameController.edgeDetect.oldSignal' (modeled as:'oldSignal.edgeDetect.gameController.model_MainClass') */
         true
      },
      /* substruct: model_MainClass_RAM.gameController.stopWatch (modeled as:'stopWatch.gameController.model_MainClass') */
      {
         /* struct element:'model_MainClass_RAM.gameController.stopWatch.timeCounter' (modeled as:'timeCounter.stopWatch.gameController.model_MainClass') */
         0.0F
      },
      /* substruct: model_MainClass_RAM.gameController.timer (modeled as:'timer.gameController.model_MainClass') */
      {
         /* struct element:'model_MainClass_RAM.gameController.timer.timeCounter' (modeled as:'timeCounter.timer.gameController.model_MainClass') */
         0.0F
      }
   },
   /* substruct: model_MainClass_RAM.ledController (modeled as:'ledController.model_MainClass') */
   {
      /* struct element:'model_MainClass_RAM.ledController.fadeValue' (modeled as:'fadeValue.ledController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.ledController.gameTime' (modeled as:'gameTime.ledController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.ledController.gameState' (modeled as:'gameState.ledController.model_MainClass') */
      0U,
      /* struct element:'model_MainClass_RAM.ledController.sm' (modeled as:'sm.ledController.model_MainClass') */
      0U /* IdleFading */,
      /* substruct: model_MainClass_RAM.ledController.ledRing (modeled as:'ledRing.ledController.model_MainClass') */
      {
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[0].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[0].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[0].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[1].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[1].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[1].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[2].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[2].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[2].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[3].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[3].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[3].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[4].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[4].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[4].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[5].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[5].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[5].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[6].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[6].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[6].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[7].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[7].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[7].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[8].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[8].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[8].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[9].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[9].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[9].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[10].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[10].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[10].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         },
         {
            /* struct element:'model_MainClass_RAM.ledController.ledRing[11].blue' (modeled as:'blue.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[11].green' (modeled as:'green.ledRing.ledController.model_MainClass') */
            0U,
            /* struct element:'model_MainClass_RAM.ledController.ledRing[11].red' (modeled as:'red.ledRing.ledController.model_MainClass') */
            0U
         }
      },
      /* substruct: model_MainClass_RAM.ledController.sw (modeled as:'sw.ledController.model_MainClass') */
      {
         /* struct element:'model_MainClass_RAM.ledController.sw.timeCounter' (modeled as:'timeCounter.sw.ledController.model_MainClass') */
         0.0F
      }
   },
   /* substruct: model_MainClass_RAM.servoController (modeled as:'servoController.model_MainClass') */
   {
      /* struct element:'model_MainClass_RAM.servoController.ballPosition' (modeled as:'ballPosition.servoController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.servoController.error' (modeled as:'error.servoController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.servoController.handPosition' (modeled as:'handPosition.servoController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.servoController.integral' (modeled as:'integral.servoController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.servoController.lastValue' (modeled as:'lastValue.servoController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.servoController.servoPosition' (modeled as:'servoPosition.servoController.model_MainClass') */
      0.0F,
      /* struct element:'model_MainClass_RAM.servoController.doIntegrate' (modeled as:'doIntegrate.servoController.model_MainClass') */
      true,
      /* struct element:'model_MainClass_RAM.servoController.gameState' (modeled as:'gameState.servoController.model_MainClass') */
      0U,
      /* struct element:'model_MainClass_RAM.servoController.sm' (modeled as:'sm.servoController.model_MainClass') */
      0U /* IdlePosition */,
      /* struct element:'model_MainClass_RAM.servoController.switchMode' (modeled as:'switchMode.servoController.model_MainClass') */
      false,
      /* substruct: model_MainClass_RAM.servoController.edgeDetect (modeled as:'edgeDetect.servoController.model_MainClass') */
      {
         /* struct element:'model_MainClass_RAM.servoController.edgeDetect.buffer' (modeled as:'buffer.edgeDetect.servoController.model_MainClass') */
         false,
         /* struct element:'model_MainClass_RAM.servoController.edgeDetect.oldSignal' (modeled as:'oldSignal.edgeDetect.servoController.model_MainClass') */
         true
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'model_MainClass_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'model_MainClass'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'model_MainClass'
 * data set:.....................................'MODEL_MAINCLASS_STM32F334R8_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct model_MainClass_stm32f334r8 model_MainClass = {
   /* substruct: model_MainClass.gameController (modeled as:'gameController.model_MainClass') */
   {
      /* type descriptor pointer 'model_GameController_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &model_MainClass_CAL_MEM.gameController,
      /* type descriptor pointer 'model_GameController_Automatic_RAM' for memory class substruct for 'RAM' */
      &model_MainClass_RAM.gameController,
      /* substruct: model_MainClass.gameController.edgeDetect (modeled as:'edgeDetect.gameController.model_MainClass') */
      {
         /* type descriptor pointer 'SystemLib_Miscellaneous_EdgeRising_Impl_RAM' for memory class substruct for 'RAM' */
         &model_MainClass_RAM.gameController.edgeDetect
      },
      /* substruct: model_MainClass.gameController.stopWatch (modeled as:'stopWatch.gameController.model_MainClass') */
      {
         /* type descriptor pointer 'SystemLib_CounterTimer_StopWatch_Automatic_RAM' for memory class substruct for 'RAM' */
         &model_MainClass_RAM.gameController.stopWatch
      },
      /* substruct: model_MainClass.gameController.timer (modeled as:'timer.gameController.model_MainClass') */
      {
         /* type descriptor pointer 'SystemLib_CounterTimer_Timer_Automatic_RAM' for memory class substruct for 'RAM' */
         &model_MainClass_RAM.gameController.timer
      }
   },
   /* substruct: model_MainClass.ledController (modeled as:'ledController.model_MainClass') */
   {
      /* type descriptor pointer 'model_LedController_stm32f334r8_RAM' for memory class substruct for 'RAM' */
      &model_MainClass_RAM.ledController,
      /* substruct: model_MainClass.ledController.sw (modeled as:'sw.ledController.model_MainClass') */
      {
         /* type descriptor pointer 'SystemLib_CounterTimer_StopWatch_Automatic_RAM' for memory class substruct for 'RAM' */
         &model_MainClass_RAM.ledController.sw
      }
   },
   /* substruct: model_MainClass.servoController (modeled as:'servoController.model_MainClass') */
   {
      /* type descriptor pointer 'model_ServoController_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &model_MainClass_CAL_MEM.servoController,
      /* type descriptor pointer 'model_ServoController_Automatic_RAM' for memory class substruct for 'RAM' */
      &model_MainClass_RAM.servoController,
      /* substruct: model_MainClass.servoController.edgeDetect (modeled as:'edgeDetect.servoController.model_MainClass') */
      {
         /* type descriptor pointer 'SystemLib_Miscellaneous_EdgeRising_Impl_RAM' for memory class substruct for 'RAM' */
         &model_MainClass_RAM.servoController.edgeDetect
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'model_MainClass'
 ******************************************************************************/





#define gameController_REF (&(model_MainClass.gameController))
#define ledController_REF (&(model_MainClass.ledController))
#define servoController_REF (&(model_MainClass.servoController))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'model_MainClass_stm32f334r8_step'
 * ----------------------------------------------------------------------------
 * model name:...................................'step'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */
#define model_Signals_autoModeButton__model_MainClass_stm32f334r8_step (model_Signals_autoModeButton)
#define model_Signals_ballPosition__model_MainClass_stm32f334r8_step (model_Signals_ballPosition)
#define model_Signals_handPosition__model_MainClass_stm32f334r8_step (model_Signals_handPosition)
#define model_Signals_ledRing__model_MainClass_stm32f334r8_step (model_Signals_ledRing)
#define model_Signals_score__model_MainClass_stm32f334r8_step (model_Signals_score)
#define model_Signals_servoPosition__model_MainClass_stm32f334r8_step (model_Signals_servoPosition)
#define model_Signals_startGameButton__model_MainClass_stm32f334r8_step (model_Signals_startGameButton)


void model_MainClass_stm32f334r8_step (void)
{
   model_MainClass_RAM.gameController.ballPosition = model_Signals_ballPosition__model_MainClass_stm32f334r8_step;
   model_MainClass_RAM.gameController.startGame
      = model_Signals_startGameButton__model_MainClass_stm32f334r8_step;
   model_GameController_Automatic_periodicTrigger(gameController_REF);
   model_Signals_score__model_MainClass_stm32f334r8_step = model_MainClass_RAM.gameController.score;
   model_MainClass_RAM.ledController.gameTime = model_GameController_Automatic_getTime(gameController_REF);
   model_MainClass_RAM.ledController.gameState = model_GameController_Automatic_gameState(gameController_REF);
   model_LedController_stm32f334r8_periodicTrigger(ledController_REF);
   memcpy(model_Signals_ledRing__model_MainClass_stm32f334r8_step , model_MainClass_RAM.ledController.ledRing , sizeof(struct model_RgbLed_stm32f334r8[12]));
   model_MainClass_RAM.servoController.gameState = model_GameController_Automatic_gameState(gameController_REF);
   model_MainClass_RAM.servoController.ballPosition = model_Signals_ballPosition__model_MainClass_stm32f334r8_step;
   model_MainClass_RAM.servoController.handPosition = model_Signals_handPosition__model_MainClass_stm32f334r8_step;
   model_MainClass_RAM.servoController.switchMode
      = model_Signals_autoModeButton__model_MainClass_stm32f334r8_step;
   model_ServoController_Automatic_periodicTrigger(servoController_REF);
   model_Signals_servoPosition__model_MainClass_stm32f334r8_step = model_MainClass_RAM.servoController.servoPosition;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'model_MainClass_stm32f334r8_step'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



